<html>
<head><meta charset="utf-8"><title>Internal Server Error while creating a new dataset · containers · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/index.html">containers</a></h2>
<h3>Topic: <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html">Internal Server Error while creating a new dataset</a></h3>

<hr>

<base href="https://dataverse.zulipchat.com">

<head><link href="https://gdcc.github.io/zulip-archive/style.css" rel="stylesheet"></head>

<a name="518082813"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518082813" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> César Ferreira <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518082813">(May 14 2025 at 14:31)</a>:</h4>
<p>Hi everyone, I have a fresh installation of Dataverse version 6.6 using Docker containers and when I try to create a new dataset it causes an Internal Server Error. The only entry I can find in server.log is the following:</p>
<div class="codehilite"><pre><span></span><code>[2025-05-14T14:26:02.331+0000] [Payara 6.2025.2] [WARNING] [] [jakarta.enterprise.web] [tid: _ThreadID=115 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1747232762331] [levelValue: 900] [[
  StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:361)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at edu.harvard.iq.dataverse.DatasetPage.resetVersionUI(DatasetPage.java:2624)
        at edu.harvard.iq.dataverse.DatasetPage.init(DatasetPage.java:2223)
        at edu.harvard.iq.dataverse.DatasetPage.init(DatasetPage.java:1933)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.glassfish.expressly.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:186)
        at org.glassfish.expressly.parser.AstValue.invoke(AstValue.java:253)
        at org.glassfish.expressly.MethodExpressionImpl.invoke(MethodExpressionImpl.java:248)
        at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
        at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:70)
        at com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:74)
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:62)
        at jakarta.faces.component.UIViewAction.broadcast(UIViewAction.java:506)
        at jakarta.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:858)
        at jakarta.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1338)
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:56)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:131)
        at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
        at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1554)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:83)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:166)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:372)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:239)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:840)
]]
</code></pre></div>
<p>Any ideas of what could be causing this error?</p>



<a name="518085239"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518085239" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518085239">(May 14 2025 at 14:40)</a>:</h4>
<p>That's the complete server.log file?</p>



<a name="518085777"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518085777" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> César Ferreira <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518085777">(May 14 2025 at 14:42)</a>:</h4>
<p>That's only the last entry from server.log, which is the only one that appears with the error.</p>



<a name="518086890"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518086890" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518086890">(May 14 2025 at 14:46)</a>:</h4>
<p>very strange</p>



<a name="518086955"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518086955" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518086955">(May 14 2025 at 14:47)</a>:</h4>
<p>So you're saying you're getting that index out of bounds exception here: <a href="https://github.com/IQSS/dataverse/blob/v6.6/src/main/java/edu/harvard/iq/dataverse/DatasetPage.java#L2624">https://github.com/IQSS/dataverse/blob/v6.6/src/main/java/edu/harvard/iq/dataverse/DatasetPage.java#L2624</a></p>



<a name="518087653"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518087653" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518087653">(May 14 2025 at 14:50)</a>:</h4>
<p>It looks like that code was touched for 6.6 in this PR: ORCID: Support authenticated ORCIDs in account profile <a href="https://github.com/IQSS/dataverse/issues/11222">#11222</a></p>



<a name="518088091"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518088091" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518088091">(May 14 2025 at 14:51)</a>:</h4>
<p>How does the author info look when you are entering it? Can you please share a screenshot?</p>



<a name="518088865"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518088865" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> César Ferreira <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518088865">(May 14 2025 at 14:54)</a>:</h4>
<p>I can't even get to the creation page, when I click on <code>New Dataset</code> it returns the Internal Server Error page. I am using the user dataverseAdmin. The line of the code you sent refers to first name and last name, which looks to be correctly set for that user.</p>



<a name="518094089"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518094089" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> César Ferreira <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518094089">(May 14 2025 at 15:14)</a>:</h4>
<p>I created a new user, to check if it was only happening for dataverseAdmin, but it looks like it is happening for all users.</p>
<p>While looking at <code>server.log</code>, I also found at the beginning  a lot of SEVERE entries like this, all for <code>.jar</code> files inside <code>/usr/local/payara6/glassfish/domains/domain1/applications/dataverse/WEB-INF/lib/</code>:</p>
<div class="codehilite"><pre><span></span><code>[2025-05-14T13:54:50.207+0000] [Payara 6.2025.2] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=166 _ThreadName=payara-executor-service-task] [timeMillis: 1747230890207] [levelValue: 1000] [[
  Exception while parsing file file:/usr/local/payara6/glassfish/domains/domain1/applications/dataverse/WEB-INF/lib/antlr4-runtime-4.12.0.jar
java.lang.RuntimeException: java.io.IOException: invalid zip file: file:/usr/local/payara6/glassfish/domains/domain1/applications/dataverse/WEB-INF/lib/antlr4-runtime-4.12.0.jar
    at com.sun.enterprise.deployment.deploy.shared.InputJarArchive.entries(InputJarArchive.java:205)
    at com.sun.enterprise.deployment.deploy.shared.InputJarArchive.entries(InputJarArchive.java:182)
    at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.onSelectedEntries(ReadableArchiveScannerAdapter.java:125)
    at org.glassfish.hk2.classmodel.reflect.Parser.doJob(Parser.java:321)
    at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:280)
    at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:269)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: invalid zip file: file:/usr/local/payara6/glassfish/domains/domain1/applications/dataverse/WEB-INF/lib/antlr4-runtime-4.12.0.jar
    at com.sun.enterprise.deployment.deploy.shared.InputJarArchive$ArchiveJarEntrySource.&lt;init&gt;(InputJarArchive.java:589)
    at com.sun.enterprise.deployment.deploy.shared.InputJarArchive.createEntryEnumeration(InputJarArchive.java:458)
    at com.sun.enterprise.deployment.deploy.shared.InputJarArchive.entries(InputJarArchive.java:203)
    ... 9 more
]]
</code></pre></div>
<p>Could this be the cause? On the dashboard page I noticed that some elements are not rendering correctly, like this:<br>
<a href="/user_uploads/53090/-iFmsFLAv8qMkd1DX_RJHwZ_/image.png">image.png</a></p>
<div class="message_inline_image"><a href="/user_uploads/53090/-iFmsFLAv8qMkd1DX_RJHwZ_/image.png" title="image.png"><img data-original-content-type="image/png" data-original-dimensions="820x439" src="/user_uploads/thumbnail/53090/-iFmsFLAv8qMkd1DX_RJHwZ_/image.png/840x560.webp"></a></div>



<a name="518097014"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518097014" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518097014">(May 14 2025 at 15:26)</a>:</h4>
<p>Strange. How are you running Dataverse? You mentioned Docker. Are you following <a href="https://guides.dataverse.org/en/6.6/container/running/demo.html">https://guides.dataverse.org/en/6.6/container/running/demo.html</a> ?</p>



<a name="518097477"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518097477" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> César Ferreira <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518097477">(May 14 2025 at 15:28)</a>:</h4>
<p>No, I am following our repository <a href="https://gitlab.com/lip-computing/dataverse">https://gitlab.com/lip-computing/dataverse</a>.</p>



<a name="518099897"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518099897" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518099897">(May 14 2025 at 15:39)</a>:</h4>
<p>As a sanity check, could you please try that "demo" tutorial?</p>



<a name="518102366"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518102366" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> César Ferreira <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518102366">(May 14 2025 at 15:49)</a>:</h4>
<p>I was using older versions of the metadatablocks <code>.tsv</code> files, thats why I was getting that index out of bounds error.</p>



<a name="518102626"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518102626" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518102626">(May 14 2025 at 15:50)</a>:</h4>
<p>Ah, sounds like you figured it out. Great!</p>



<a name="518103255"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518103255" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> César Ferreira <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518103255">(May 14 2025 at 15:53)</a>:</h4>
<p>Thank you for the help <span class="user-mention" data-user-id="598112">@Philip Durbin ☀️</span> .<br>
Two more things:</p>
<ul>
<li>
<p>This problem is probably happening because of the language packages, right?<br>
<a href="/user_uploads/53090/O1Nmec1Aq0CheKYuMI4RcmX-/image.png">image.png</a></p>
<div class="message_inline_image"><a href="/user_uploads/53090/O1Nmec1Aq0CheKYuMI4RcmX-/image.png" title="image.png"><img data-original-content-type="image/png" data-original-dimensions="524x242" src="/user_uploads/thumbnail/53090/O1Nmec1Aq0CheKYuMI4RcmX-/image.png/840x560.webp"></a></div></li>
<li>
<p>Regarding the SEVERE log entries for the <code>.jar</code> files, any idea of what could be causing them?</p>
</li>
</ul>



<a name="518103512"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518103512" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518103512">(May 14 2025 at 15:54)</a>:</h4>
<p>Yes, the ??? is probably from out of date properties files.</p>



<a name="518103940"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518103940" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518103940">(May 14 2025 at 15:56)</a>:</h4>
<p>I'm not sure what to say about the jar file. I have it locally too:</p>
<div class="codehilite"><pre><span></span><code>% find . | grep antlr4-runtime
./target/dataverse/WEB-INF/lib/antlr4-runtime-4.12.0.jar
./target/docker/gdcc/dataverse/unstable/build/maven/deps/antlr4-runtime-4.12.0.jar
</code></pre></div>
<p><span class="user-mention" data-user-id="598183">@Oliver Bertuch</span> might know. He contributes to Payara.</p>



<a name="518105328"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518105328" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> César Ferreira <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518105328">(May 14 2025 at 16:01)</a>:</h4>
<p>For the language packages I am using the ones from <a href="https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs.git">https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs.git</a> version 6.4. I searched in <code>Bundle.properties</code> and the var names do not match with the ones presented <a href="https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/blob/bf38c1607f87574a6a33c3f5d9d27b7c162de604/en_US/Bundle.properties#L525">https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/blob/bf38c1607f87574a6a33c3f5d9d27b7c162de604/en_US/Bundle.properties#L525</a>:<br>
<a href="/user_uploads/53090/ct5-Qd1oKq7t_ONI8k1TwuYj/image.png">image.png</a></p>
<div class="message_inline_image"><a href="/user_uploads/53090/ct5-Qd1oKq7t_ONI8k1TwuYj/image.png" title="image.png"><img data-original-content-type="image/png" data-original-dimensions="1129x347" src="/user_uploads/thumbnail/53090/ct5-Qd1oKq7t_ONI8k1TwuYj/image.png/840x560.webp"></a></div>



<a name="518106175"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518106175" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518106175">(May 14 2025 at 16:04)</a>:</h4>
<p>Hmm, Jayanthy knows more about that repo than I do. You could open an issue.</p>



<a name="518106240"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518106240" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518106240">(May 14 2025 at 16:04)</a>:</h4>
<p>What if you get them from <a href="https://github.com/IQSS/dataverse/tree/v6.4">https://github.com/IQSS/dataverse/tree/v6.4</a> ?</p>



<a name="518107073"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518107073" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> César Ferreira <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518107073">(May 14 2025 at 16:08)</a>:</h4>
<p>Actually I am using Dataverse v6.6, the language packages are v6.4 just because it is the most recent version available on that repository. For now I can remove these packages and use the ones that come bundled with Dataverse by default.</p>



<a name="518107539"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/Internal%20Server%20Error%20while%20creating%20a%20new%20dataset/near/518107539" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Philip Durbin 🚀 <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/Internal.20Server.20Error.20while.20creating.20a.20new.20dataset.html#518107539">(May 14 2025 at 16:11)</a>:</h4>
<p>Sure, sounds good.</p>



<hr><p>Last updated: Nov 01 2025 at 23:12 UTC</p>
</html>