[
    {
        "content": "<p>Hi there again. I just upgraded from 6.4 to 6.5 and while I can create a new dataset, when I do any kind of search the new dataset does not show up. The count by subject increments as expected but the total dataset count when I do an advanced search does not. I get an email saying the dataset was successfully created and when I click the link that way I can find the dataset. I'm not getting any errors in the log. Any ideas on what might be going on?</p>",
        "id": 505474529,
        "sender_full_name": "Jay Sundu",
        "timestamp": 1741884579
    },
    {
        "content": "<p>Can you see the new dataset when you browse around?</p>",
        "id": 505492653,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741889343
    },
    {
        "content": "<p>I can see the new dataset but I can only get to it via the link in the email. I can't browse to it from anywhere else.</p>",
        "id": 505494419,
        "sender_full_name": "Jay Sundu",
        "timestamp": 1741889789
    },
    {
        "content": "<p>Ok, that makes sense. Both search and browse are not working. What if you try to reindex that dataset? <a href=\"https://guides.dataverse.org/en/6.5/admin/solr-search-index.html#reindexing-datasets\">https://guides.dataverse.org/en/6.5/admin/solr-search-index.html#reindexing-datasets</a></p>\n<p>No errors in server.log?</p>",
        "id": 505494724,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741889881
    },
    {
        "content": "<p>There are no errors in server.log. I tried to reindex just that dataset with no luck . I just tried clearing all data from Solr and reindexing everything and now I cannot search nor browse any of the datasets.</p>",
        "id": 505498125,
        "sender_full_name": "Jay Sundu",
        "timestamp": 1741890798
    },
    {
        "content": "<p>Usually in cases like this server.log will tell you what's wrong. Often it's a field that needs to be added to Solr's schema.xml.</p>",
        "id": 505498356,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741890858
    },
    {
        "content": "<p>Have you tried looking at Solr logs?</p>",
        "id": 505498384,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741890864
    },
    {
        "content": "<p>I do see this now in the server.log <code>contentInDatabaseButStaleInOrMissingFromIndex</code> and in the solr.log I see <code>unknown field 'fileCount'</code></p>",
        "id": 505499586,
        "sender_full_name": "Jay Sundu",
        "timestamp": 1741891161
    },
    {
        "content": "<p>Right. You need that fileCount field.</p>",
        "id": 505499844,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741891233
    },
    {
        "content": "<p>It looks like it was added in 6.5 in <a href=\"https://github.com/IQSS/dataverse/pull/10598\">https://github.com/IQSS/dataverse/pull/10598</a></p>",
        "id": 505500032,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741891287
    },
    {
        "content": "<p>Please see the steps about updating schema.xml at <a href=\"https://github.com/IQSS/dataverse/releases/tag/v6.5\">https://github.com/IQSS/dataverse/releases/tag/v6.5</a></p>",
        "id": 505500234,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741891341
    },
    {
        "content": "<p>Is that step 7a in the directions? I did run that before and just did it again and the fileCount field is still showing as missing. I also did a the reindex step.</p>",
        "id": 505500945,
        "sender_full_name": "Jay Sundu",
        "timestamp": 1741891561
    },
    {
        "content": "<p>Oh wait, I see it may be step 7. I just ran that step too.</p>",
        "id": 505501473,
        "sender_full_name": "Jay Sundu",
        "timestamp": 1741891706
    },
    {
        "content": "<p>I see what I'm doing wrong. Hold on.</p>",
        "id": 505502291,
        "sender_full_name": "Jay Sundu",
        "timestamp": 1741891950
    },
    {
        "content": "<p>I figured out I was using an older copy of schema.xml and not the newest one. Thanks <span class=\"user-mention\" data-user-id=\"598112\">@Philip Durbin ☀️</span></p>",
        "id": 505502647,
        "sender_full_name": "Jay Sundu",
        "timestamp": 1741892059
    },
    {
        "content": "<p>Working now? Great!</p>",
        "id": 505505369,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741892894
    },
    {
        "content": "<p>Yes. It's working now. Thanks again!</p>",
        "id": 505507641,
        "sender_full_name": "Jay Sundu",
        "timestamp": 1741893627
    },
    {
        "content": "<p>phew <span aria-label=\"big smile\" class=\"emoji emoji-1f604\" role=\"img\" title=\"big smile\">:big_smile:</span></p>",
        "id": 505507716,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741893653
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"598112\">Philip Durbin ☀️</span> has marked this topic as resolved.</p>",
        "id": 505517822,
        "sender_full_name": "Notification Bot",
        "timestamp": 1741897170
    }
]