[
    {
        "content": "<p>Anyone know if there is anything in the v6.2 upgrade that would affect shibboleth? I upgraded our production site this past weekend and am seeing errors in the system log related to shibboleth (ie: \" Unable to locate metadata for identity provider\") and periodically folks can't login</p>",
        "id": 440193106,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1716415879
    },
    {
        "content": "<p>Hmm. We're running 6.2 at Harvard and Shibboleth is working fine.</p>",
        "id": 440199523,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1716418665
    },
    {
        "content": "<p>That error doesn't seem to be coming from Dataverse itself. Rather, it's coming from Shibboleth: <a href=\"https://stackoverflow.com/questions/24261141/unable-to-locate-metadata-for-identity-provider\">https://stackoverflow.com/questions/24261141/unable-to-locate-metadata-for-identity-provider</a></p>",
        "id": 440199709,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1716418737
    },
    {
        "content": "<p>yea, sorry, i was just going to try to delete that post as I think it is something wrong with our shib config .. it is actually happening on our QA site and not production, so something got messed up there .. thanks for the response .. i'll close this <span aria-label=\"smile\" class=\"emoji emoji-1f642\" role=\"img\" title=\"smile\">:smile:</span></p>",
        "id": 440200354,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1716418945
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"598843\">Deirdre Kirmis</span> has marked this topic as resolved.</p>",
        "id": 440200431,
        "sender_full_name": "Notification Bot",
        "timestamp": 1716418984
    }
]