[
    {
        "content": "<p>Hello .. me again with a probably stupid question .. I admit I set up our dataverse harvesting server when I first installed the site and really haven't touched it since. I only have the DEFAULT no name set that doesn't have a \"setspec\" set and should be all published datasets right? Anyway, I've noticed recently that <a href=\"https://dataverse.asu.edu/oai?verb=ListIdentifiers&amp;metadataPrefix=oai_dc\">the feed</a> is missing some datasets .. specifically there should be 83 and there are only 79. I've recently upgraded to v6.5 and did a full index of the site at that time. Should I delete/recreate the set and/or create a set that is explicitly defined? Or, any ideas why else datasets would be missing or how I can fix?</p>",
        "id": 499084106,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739302315
    },
    {
        "content": "<p>when i try to re-run the default export i see these messages in the log (and it just hangs forever and never completes):</p>\n<p>[[setService, findAllNamedSets; query: select object(o) from OAISet as o where o.spec != '' order by o.spec]]<br>\n[[ 0 results found.]]</p>",
        "id": 499084532,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739302492
    },
    {
        "content": "<p>What have I completely messed up?</p>",
        "id": 499084605,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739302520
    },
    {
        "content": "<p>Hmm, yep, should be all. I'm not sure why a few are missing. I'm also not sure if Solr is involved or not. <span aria-label=\"thinking\" class=\"emoji emoji-1f914\" role=\"img\" title=\"thinking\">:thinking:</span></p>",
        "id": 499084629,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739302533
    },
    {
        "content": "<p>Yeah, it does look like Solr is involved.</p>",
        "id": 499085253,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739302774
    },
    {
        "content": "<p>Do you see something like this in your logs?</p>\n<p>\"set query expanded to \" + datasetIds.size() + \" datasets.\"</p>",
        "id": 499085289,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739302787
    },
    {
        "content": "<p>I think harvesting might have its own log, apart from server.log I mean.</p>",
        "id": 499085423,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739302843
    },
    {
        "content": "<p>Actually, I take it back. I don't think Solr is involved for the default set.</p>",
        "id": 499085541,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739302897
    },
    {
        "content": "<div class=\"codehilite\"><pre><span></span><code>if (!oaiSet.isDefaultSet()) {\n    datasetIds = expandSetQuery(query);\n    exportLogger.info(&quot;set query expanded to &quot; + datasetIds.size() + &quot; datasets.&quot;);\n} else {\n    // The default set includes all the local, published datasets.\n    // findAllLocalDatasetIds() finds the ids of all the local datasets -\n    // including the unpublished drafts and deaccessioned ones.\n    // Those will be filtered out further down the line.\n    datasetIds = datasetService.findAllLocalDatasetIds();\n    databaseLookup = true;\n}\n</code></pre></div>",
        "id": 499085571,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739302910
    },
    {
        "content": "<p>yes, i do see that .. and it looked like it was recreating the missing datasets, and maybe i just didn't wait long enough .. <br>\n.. i also created a new set and used the example for pulling the identifier .. and it looked like it was going to export 83 records as well .. <br>\n.. so wonder why the original set stopped updating?</p>",
        "id": 499085660,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739302938
    },
    {
        "content": "<p>Not sure. Strange. Please feel free to open a issue if you think it's a bug.</p>",
        "id": 499085777,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739303004
    },
    {
        "content": "<p>ohhh okay, so the new set i created says \"83 datasets (79 records exported, 0 marked as deleted)\" .. so it is not exporting 4 for some reason</p>",
        "id": 499086069,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739303101
    },
    {
        "content": "<p>the actual OAI log just says \"Calling OAI Record Service to re-export 93 datasets.\"</p>",
        "id": 499086255,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739303168
    },
    {
        "content": "<p>Weird. I wonder if we'll be able to reproduce it, though. It is particular to your database? <span aria-label=\"thinking\" class=\"emoji emoji-1f914\" role=\"img\" title=\"thinking\">:thinking:</span></p>",
        "id": 499086282,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739303181
    },
    {
        "content": "<p>93? that would include the unpublished ones i think</p>",
        "id": 499086288,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739303184
    },
    {
        "content": "<p>i just don't know how to figure out why it isn't exporting those 4 .. they are from various time periods and don't seem to have weird formatting .. although there are some differences in all of them</p>",
        "id": 499086537,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739303279
    },
    {
        "content": "<p>What if you make a set with one of the missing datasets? Does it work?</p>",
        "id": 499086838,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739303366
    },
    {
        "content": "<p>trying now ..</p>",
        "id": 499087203,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739303511
    },
    {
        "content": "<p>it says \"1 dataset (0 records exported, 0 marked as deleted)\"</p>",
        "id": 499088097,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739303854
    },
    {
        "content": "<p>it finds the dataset but can't export those particular ones for some reason</p>",
        "id": 499088286,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739303913
    },
    {
        "content": "<p>And if you create a set for a working dataset? Does it say 1 exported?</p>",
        "id": 499088354,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739303943
    },
    {
        "content": "<p>yes it worked</p>",
        "id": 499089955,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739304532
    },
    {
        "content": "<p>ok, so something is wrong with those few, hmm <span aria-label=\"thinking\" class=\"emoji emoji-1f914\" role=\"img\" title=\"thinking\">:thinking:</span></p>",
        "id": 499090553,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739304742
    },
    {
        "content": "<p>anything in server.log?</p>",
        "id": 499090571,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739304749
    },
    {
        "content": "<p>the only thing that i'm seeing in server.log are messages like this:</p>\n<p>[2025-02-11T20:09:02.324+0000] [Payara 6.2024.7] [INFO] [] [edu.harvard.iq.dataverse.harvest.server.OAISetServiceBean] [tid: _ThreadID=93 _ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1739304542324] [levelValue: 800] [[<br>\n  setService, findAllNamedSets; query: select object(o) from OAISet as o where o.spec != '' order by o.spec]]</p>\n<p>[2025-02-11T20:09:02.325+0000] [Payara 6.2024.7] [INFO] [] [edu.harvard.iq.dataverse.harvest.server.OAISetServiceBean] [tid: _ThreadID=93 _ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1739304542325] [levelValue: 800] [[<br>\n  3 results found.]]</p>",
        "id": 499091034,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739304942
    },
    {
        "content": "<p>but that looks like the \"all published\" set and not sure why it just says \"3 results found\"??</p>",
        "id": 499091141,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739304972
    },
    {
        "content": "<p>Hi, <br>\nYes, \"83 datasets (79 records exported ...\" would almost certainly indicate that the search query has found 83 published datasets, but only 79 of them have been successfully exported, so, the remaining 4 were not included in the OAI set advertised to the clients. <br>\nYou already know the actual DOIs of the 4 missing/un-unexported datasets, correct? (ok, it looks like you know at least one - the one you've tried creating a set with...)<br>\nFirst step would be to identify which of the metadata formats is failing to export. (So, yes, this is a limitation of our export system - it's kind of binary/all-or-nothing; it's enough for just one format out of 10+ to fail, for the dataset to end up being \"unexported\". Which is a bit counter-productive, for the purposes of OAI especially - since the 3 formats needed for that are somewhat less likely to fail...)<br>\nTake a look at the storage folder for the dataset in question, on the filesystem or on S3, whichever is the case, and look for the files with the names like <code>export_*.cached</code> - for example, <code>export_oai_dc.cached</code> etc., and see which ones are missing, when compared to one of the successfully exported datasets. <br>\nOnce you see which formats are missing, try exporting them individually via </p>\n<div class=\"codehilite\"><pre><span></span><code>curl &quot;http://localhost:8080/api/datasets/export?exporter=xxx&amp;persistentId=yyy&quot;\n</code></pre></div>\n<p>while watching the server log; and hopefully there will be some errors/exceptions that will tell us what Dataverse doesn't like in the metadata. (during a bulk export of an OAI set error messages are suppressed, I believe). <br>\nThis is pretty time-consuming, unfortunately. (but maybe someone can chime in with something easier in mind)</p>",
        "id": 499091382,
        "sender_full_name": "Leo Andreev",
        "timestamp": 1739305074
    },
    {
        "content": "<p>for one of the datasets, in the storage location I see \"export_Datacite.cache\", \"export_oai_dc.cache\" and \"export_OAI_ORE.cache\" ..</p>\n<p>I tried the curl command for all three exporters for a dataset id that did export and for one that did not, and they all seemed to work .. nothing appears in server.log</p>",
        "id": 499092924,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739305727
    },
    {
        "content": "<p>these curl commands: <br>\ncurl \"<a href=\"http://localhost:8080/api/datasets/export?exporter=oai_dc&amp;persistentId=doi:&lt;ours&gt;/C1CWX9\">http://localhost:8080/api/datasets/export?exporter=oai_dc&amp;persistentId=doi:&lt;ours&gt;/C1CWX9</a>\"<br>\ncurl \"<a href=\"http://localhost:8080/api/datasets/export?exporter=OAI_ORE&amp;persistentId=doi:&lt;ours&gt;/C1CWX9\">http://localhost:8080/api/datasets/export?exporter=OAI_ORE&amp;persistentId=doi:&lt;ours&gt;/C1CWX9</a>\"<br>\ncurl \"<a href=\"http://localhost:8080/api/datasets/export?exporter=Datacite&amp;persistentId=doi:&lt;ours&gt;/C1CWX9\">http://localhost:8080/api/datasets/export?exporter=Datacite&amp;persistentId=doi:&lt;ours&gt;/C1CWX9</a>\"</p>",
        "id": 499093057,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739305787
    },
    {
        "content": "<p>all of those seemed to generate results for the non-exported dataset</p>",
        "id": 499093196,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739305829
    },
    {
        "content": "<p>looking at one of the datasets that is working, it has  more \"export\" files in the storage location .. ie: ddi, dcterms, dc, <a href=\"http://schema.org\">schema.org</a>, etc</p>",
        "id": 499094162,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739306270
    },
    {
        "content": "<p>Yes, so, the next step should be to try the export API for the formats that are NOT there/not cached. <br>\nNote that if there are a few formats that are missing, it does NOT mean that all of them have failed to export; it may just mean that the exporter stopped once it encountered the first format it wasn't able to produce.</p>",
        "id": 499094248,
        "sender_full_name": "Leo Andreev",
        "timestamp": 1739306303
    },
    {
        "content": "<p>so try each of these?:<br>\n<a href=\"https://guides.dataverse.org/en/latest/api/native-api.html#export-metadata-of-a-dataset-in-various-formats\">https://guides.dataverse.org/en/latest/api/native-api.html#export-metadata-of-a-dataset-in-various-formats</a></p>",
        "id": 499094809,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739306569
    },
    {
        "content": "<p>the oai_datacite one failed (but the Datacite one worked)</p>",
        "id": 499095479,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739306862
    },
    {
        "content": "<p>and this in the log: <br>\n IllegalStateException caught when exporting oai_datacite for dataset doi:10.48349/ASU/C1CWX9; may or may not be due to a mismatch between an exporter code and a metadata block update.</p>",
        "id": 499095690,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739306947
    },
    {
        "content": "<p>how do i fix it? <span aria-label=\"sweat smile\" class=\"emoji emoji-1f605\" role=\"img\" title=\"sweat smile\">:sweat_smile:</span></p>",
        "id": 499095724,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739306966
    },
    {
        "content": "<p>we dont' have any custom metadata blocks .. other than the computational workflow one that I accidentally installed</p>",
        "id": 499095844,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739307007
    },
    {
        "content": "<p>\"may or may not\"</p>\n<p>just tell me!</p>",
        "id": 499096225,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739307171
    },
    {
        "content": "<p>haha yea!</p>",
        "id": 499096249,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739307186
    },
    {
        "content": "<p>Yes! Except you _may_ have more metadata formats configured, on top of the 9 listed in the guide. (for example, we also have \"croissant\" added). So, comparing to what's cached in one of the known exported datasets directories may be the safest... <br>\nOK, sounds like you have already found one that is failing. The error message in the log is not super helpful, unfortunately... if you haven't yet, could you please try all the remaining formats too, and _maybe_ we'll see something more interesting in the log?</p>",
        "id": 499096277,
        "sender_full_name": "Leo Andreev",
        "timestamp": 1739307199
    },
    {
        "content": "<p>and tell me what it is and how to fix it <span aria-label=\"smile\" class=\"emoji emoji-1f642\" role=\"img\" title=\"smile\">:smile:</span></p>",
        "id": 499096282,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739307205
    },
    {
        "content": "<p>The comment above the error is not very promising: <a href=\"https://github.com/IQSS/dataverse/blob/v6.5/src/main/java/edu/harvard/iq/dataverse/export/ExportService.java#L340\">https://github.com/IQSS/dataverse/blob/v6.5/src/main/java/edu/harvard/iq/dataverse/export/ExportService.java#L340</a></p>",
        "id": 499096456,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739307276
    },
    {
        "content": "<p>i tried all of these: <code>ddi</code>, <code>oai_ddi</code>, <code>dcterms</code>, <code>oai_dc</code>, <code>schema.org</code> , <code>OAI_ORE</code> , <code>Datacite</code>, <code>oai_datacite</code> and <code>dataverse_json</code></p>\n<p>and the only one that failed was the oai_datacite one</p>",
        "id": 499096481,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739307289
    },
    {
        "content": "<p>Which dataset is failing? Can you please give us the doi or landing page?</p>",
        "id": 499096814,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739307420
    },
    {
        "content": "<p>... Another (also very time-consuming) way of going about it is to open the full metadata edit form for this dataset, next to one for one of the known \"good\" datasets, and then stare at the two looking for any visible differences. Some obscure field of which you have 2 populated entries in the former, but only one in the latter, etc.</p>",
        "id": 499096828,
        "sender_full_name": "Leo Andreev",
        "timestamp": 1739307424
    },
    {
        "content": "<p>(I'm wondering if this fix will help: Openaire fix for multiple productionPlaces <a href=\"https://github.com/IQSS/dataverse/issues/11194\">#11194</a> )</p>",
        "id": 499096846,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739307435
    },
    {
        "content": "<p>Finally, since the formats that the OAI server _actually needs_ have been exported successfully,  let me think of a way to cheat and mark the dataset as \"exported\", for the purposes of adding it to the OAI set.</p>",
        "id": 499097065,
        "sender_full_name": "Leo Andreev",
        "timestamp": 1739307507
    },
    {
        "content": "<p>okay, i will start working on comparing the metadata .. i was doing that and didn't really see anything but i understand better now what i am looking for</p>",
        "id": 499097148,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739307541
    },
    {
        "content": "<p>Multiple productionPlace:</p>\n<div class=\"codehilite\"><pre><span></span><code>          {\n            &quot;typeName&quot;: &quot;productionPlace&quot;,\n            &quot;multiple&quot;: true,\n            &quot;typeClass&quot;: &quot;primitive&quot;,\n            &quot;value&quot;: [\n              &quot;Phoenix, Arizona, USA&quot;,\n              &quot;Los Angeles, California, USA&quot;,\n              &quot;Santa Barbara, California, USA&quot;,\n              &quot;Austin, Texas, USA&quot;\n            ]\n          },\n</code></pre></div>\n<p>At <a href=\"https://dataverse.asu.edu/dataset.xhtml?persistentId=doi:10.48349/ASU/C1CWX9\">https://dataverse.asu.edu/dataset.xhtml?persistentId=doi:10.48349/ASU/C1CWX9</a></p>",
        "id": 499097156,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739307544
    },
    {
        "content": "<p>thank you both!</p>",
        "id": 499097175,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739307551
    },
    {
        "content": "<p>So for that dataset, <a href=\"https://github.com/IQSS/dataverse/issues/11194\">#11194</a> should help. (Thank you, <span class=\"user-mention\" data-user-id=\"671970\">@Florian Fritze</span> !)</p>",
        "id": 499097251,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739307583
    },
    {
        "content": "<p>yay! okay have to go to a meeting then will read/try it</p>",
        "id": 499097311,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739307608
    },
    {
        "content": "<p>The fix in the PR above will only be added in 6.6.<br>\nIf you are willing to resort to hacks, you could try and set the <code>lastexporttime</code> to some time today in the <code>dataset</code> table for this dataset, and re-export the OAI set again. (I would only try that with datasets for which at least the <code>oai_dc</code> format exports successfully). May or may not work, no promises. :)</p>",
        "id": 499098707,
        "sender_full_name": "Leo Andreev",
        "timestamp": 1739308126
    },
    {
        "content": "<p>oh got it .. i will try updating the table .. that sounds like a good solution for now if it works!</p>",
        "id": 499103998,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739310400
    },
    {
        "content": "<p>looking at the rest of the datasets that won't export to see if it is the same thing</p>",
        "id": 499104108,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739310455
    },
    {
        "content": "<p>they do all have multiple production locations</p>",
        "id": 499104325,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739310546
    },
    {
        "content": "<p>the db hack worked at least for that one dataset .. trying the rest</p>",
        "id": 499107811,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739312102
    },
    {
        "content": "<p>THANK YOU!! <span aria-label=\"tada\" class=\"emoji emoji-1f389\" role=\"img\" title=\"tada\">:tada:</span></p>",
        "id": 499107837,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739312114
    },
    {
        "content": "<p>well, it worked for the new oai set that i created with the persistent id set, but not for the default dataset .. it still says 79 .. wonder why? we will probably need to change our primo feed to point to the new one i guess</p>",
        "id": 499108220,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739312293
    },
    {
        "content": "<p>and it worked for 2 of the datasets but not the other 2 .. <span aria-label=\"confused\" class=\"emoji emoji-1f615\" role=\"img\" title=\"confused\">:confused:</span></p>",
        "id": 499109028,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739312705
    },
    {
        "content": "<p>when i point to one of the \"fixed\" ones it says it has been deleted<br>\n<a href=\"https://dataverse.asu.edu/oai?verb=GetRecord&amp;identifier=doi%3A10.48349%2FASU%2FC1CWX9&amp;metadataPrefix=oai_dc\">https://dataverse.asu.edu/oai?verb=GetRecord&amp;identifier=doi%3A10.48349%2FASU%2FC1CWX9&amp;metadataPrefix=oai_dc</a></p>",
        "id": 499110592,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739313441
    },
    {
        "content": "<p>I'm sorry I sent you on this hacky path!<br>\nLet's try and erase and rebuild the default set from scratch; but if these datasets are still left out of it after that, I think the sensible thing to do will be to wait for 6.6 to fix it properly<br>\nSo, first, please erase all the records in the default set: <br>\n<code>DELETE FROM oairecord WHERE setname = '';</code><br>\n(please be super careful! deleting things from the database directly is inherently risky...)<br>\nAfter that, the control panel should be showing \"no active records\" for the default set. Then re-export the set, and see what happens.</p>",
        "id": 499242694,
        "sender_full_name": "Leo Andreev",
        "timestamp": 1739369149
    },
    {
        "content": "<p>ha no worries I always learn things that I didn't know doing hacky things! <span aria-label=\"big smile\" class=\"emoji emoji-1f604\" role=\"img\" title=\"big smile\">:big_smile:</span>  I would like to clean up that default set anyway. Will do this morning.</p>",
        "id": 499255652,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739372473
    },
    {
        "content": "<p>well, it's better, it is now showing 81 rows .. so it included 2 of the ones that were missing before but 2 are still missing .. I'll figure out which ones are still missing and look at the metadata and see if there is anything else that could be causing this .. otherwise we will wait for the fix! <span aria-label=\"smile\" class=\"emoji emoji-1f642\" role=\"img\" title=\"smile\">:smile:</span></p>",
        "id": 499258720,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739373211
    },
    {
        "content": "<p>thanks so much for your help! <span aria-label=\"glowing star\" class=\"emoji emoji-1f31f\" role=\"img\" title=\"glowing star\">:glowing_star:</span></p>",
        "id": 499258807,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739373234
    },
    {
        "content": "<p>Well, we are 2 datasets better off than we were yesterday, so I'll call it progress :)</p>",
        "id": 499271115,
        "sender_full_name": "Leo Andreev",
        "timestamp": 1739376237
    },
    {
        "content": "<p>ha yes for sure! <br>\nThe 2 datasets still not showing are:<br>\n<a href=\"https://dataverse.asu.edu/dataset.xhtml?persistentId=doi:10.48349/ASU/7DCWIK\">https://dataverse.asu.edu/dataset.xhtml?persistentId=doi:10.48349/ASU/7DCWIK</a><br>\n<a href=\"https://dataverse.asu.edu/dataset.xhtml?persistentId=doi:10.48349/ASU/C1CWX9\">https://dataverse.asu.edu/dataset.xhtml?persistentId=doi:10.48349/ASU/C1CWX9</a></p>\n<p>They both have multiple production locations. I tried changing the lastexporttime for both to an earlier date (most of them show november '24) .. but it didn't make a difference, still didn't show in the feed after re-export. </p>\n<p>I guess we could try deleting all but one of the production locations until the fix is released and see if that works, and then add them back after the fix.</p>",
        "id": 499277060,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739377756
    },
    {
        "content": "<p>Should work, unless that exporter is failing for more reasons than just Production Place.</p>",
        "id": 499279156,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1739378319
    },
    {
        "content": "<p>And maybe double-check the <code>lastexporttime</code> in the <code>dataset</code> table for these 2, that it is actually something later than the <code>releasetime</code> on their latest datasetversions - ?</p>",
        "id": 499282816,
        "sender_full_name": "Leo Andreev",
        "timestamp": 1739379330
    },
    {
        "content": "<p>ohhhhhh that was it! The release date on those 2 was blank again (maybe because I tried to set it earlier?) .. idk .. but i made sure the lastexportdate was later than the release date, and now everything is showing as exported! I swear, yesterday when i did this I set them all to yesterday's date and it didn't work .. but for some reason those had to be set again. THANK YOU! We are good for now but will wait for the fix!</p>",
        "id": 499293949,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1739382573
    }
]