[
    {
        "content": "<p>Hello everyone, how are you?</p>\n<p>I have been trying to upgrade my Dataverse installation, from 5.14 to 6.2, but I have had a problem deploying the dataverse war file. The problem is with postgres.</p>\n<p>I have created a new database, but the problem continues. There is an image showing the problem.</p>\n<p><a href=\"/user_uploads/53090/19kPYEoBWfdEVkYd92TzLY53/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/19kPYEoBWfdEVkYd92TzLY53/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/19kPYEoBWfdEVkYd92TzLY53/image.png\"></a></div><p>Does anyone know what I should do?</p>",
        "id": 442829526,
        "sender_full_name": "Santiago Florez",
        "timestamp": 1717603703
    },
    {
        "content": "<p>I downloaded the war file from <a href=\"https://github.com/IQSS/dataverse/releases/tag/v6.2\">https://github.com/IQSS/dataverse/releases/tag/v6.2</a></p>\n<p><a href=\"/user_uploads/53090/HefY3dlWlzQVr3IIqD-7lyyG/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/HefY3dlWlzQVr3IIqD-7lyyG/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/HefY3dlWlzQVr3IIqD-7lyyG/image.png\"></a></div>",
        "id": 442831830,
        "sender_full_name": "Santiago Florez",
        "timestamp": 1717604178
    },
    {
        "content": "<p>Hi! First, you have to upgrade to 6.0, then 6.1, then 6.2.</p>\n<p>Second, can you please show us server.log?</p>",
        "id": 442857716,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1717610821
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"598112\">@Philip Durbin</span> thanks for answer, so, I'm gonna upgrade version by version.</p>\n<p>This is the log file.<br>\n<a href=\"/user_uploads/53090/oB0sgSlit_wlIBBJMuqpUmvi/Error_Dataverse6.2.txt\">Error_Dataverse6.2.txt</a></p>",
        "id": 442859702,
        "sender_full_name": "Santiago Florez",
        "timestamp": 1717611470
    },
    {
        "content": "<p>I don't understand why I have this postgres error</p>",
        "id": 442860569,
        "sender_full_name": "Santiago Florez",
        "timestamp": 1717611748
    },
    {
        "content": "<p>Did you do this step from <a href=\"https://github.com/IQSS/dataverse/releases/tag/v6.0\">https://github.com/IQSS/dataverse/releases/tag/v6.0</a> ?</p>\n<p><code>sudo -u dataverse /usr/local/payara6/bin/asadmin create-jvm-options --add-opens=java.base/java.io=ALL-UNNAMED</code></p>\n<p>I'm asking because in your log I see <code>module java.base does not \"opens java.io\" to unnamed module</code> and I'm reminded of <a href=\"https://github.com/IQSS/dataverse/issues/10068\">#10068</a>.</p>",
        "id": 442861734,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1717612178
    },
    {
        "content": "<p>Hi <span class=\"user-mention\" data-user-id=\"598112\">@Philip Durbin</span> I have decided to install the new dataverse version from scratch. Thank goodness I didn't have any information loaded yet.</p>",
        "id": 443098731,
        "sender_full_name": "Santiago Florez",
        "timestamp": 1717689560
    },
    {
        "content": "<p>Sounds easier!</p>",
        "id": 443124772,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1717696855
    },
    {
        "content": "<p>I noticed Harvard is at 6.2, but this version: v. 6.2 build \"v6.2+10451+10463+10383-iqss\"</p>\n<p>Any special reason why this not \"the\" 6.2 release? </p>\n<p>UVa is upgrading from 5.14 to 6.2 next week and am wondering about running into problems. There seem to be a few folks have encountered (from the Dataverse google group and here on Zulip).</p>",
        "id": 443284740,
        "sender_full_name": "Sherry Lake",
        "timestamp": 1717762176
    },
    {
        "content": "<p>As you might guess, <a href=\"https://github.com/IQSS/dataverse/issues/10451\">#10451</a> <a href=\"https://github.com/IQSS/dataverse/issues/10463\">#10463</a> and <a href=\"https://github.com/IQSS/dataverse/issues/10383\">#10383</a> are all pull requests:</p>\n<ul>\n<li>IQSS/10450 - Fixes for Globus download (transfer out) and related info messages <a href=\"https://github.com/IQSS/dataverse/issues/10451\">#10451</a></li>\n<li>IQSS/10462 - Fix when MDC is displayed <a href=\"https://github.com/IQSS/dataverse/issues/10463\">#10463</a></li>\n<li>Resolve performance issues with large datasets <a href=\"https://github.com/IQSS/dataverse/issues/10383\">#10383</a></li>\n</ul>\n<p>I guess these are all fixes we needed for Harvard Dataverse. They will all be included in 6.3.</p>",
        "id": 443298049,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1717766728
    },
    {
        "content": "<p>I'm finally able to list buckets via aws cli.  Â The production bucket policy doesn't have an explicate line for listing the bucket and doesn't seem to need it.Â  But I aded the explict list (\"Action\": \"s3:ListBucket\",) to dataverse-test-oregon and suddenly I could list it with aws cli.<br>\nI'm not sure what the difference is but will do this for the new production system.   <br>\nBack to  shibboleth and doi setup correctly in domain.xml.</p>",
        "id": 444356938,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718239446
    },
    {
        "content": "<p>s3 bucket issues.   The production bucket policy (RHEL 7) doesn't have an explicate line for listing the bucket and doesn't seem to need it.Â  But I aded the explict list (\"Action\": \"s3:ListBucket\",) to dataverse-test-oregon and suddenly I could list it with aws cli.  I don't know if this is a difference between the 5.14 and 6.2 but I'm going to follow this example for the production 6.2.</p>",
        "id": 444519506,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718299442
    },
    {
        "content": "<p>Hmm, it this something we should fix in our guides?</p>",
        "id": 444520651,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718299699
    },
    {
        "content": "<p>I haven't installed a clean system since 4.11 or there about.  It seems that what worked up to 5.14 is different in 6.2.   Bit of a jump between versions so I may have missed something.    Examples for the pid/doi settings might be helpful.  I'll post mine when I get through this install.</p>",
        "id": 444521481,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718299989
    },
    {
        "content": "<p>Sorry,  I just realized I posted in the wrong place.  I'm limping through 5.14 to 6.2</p>",
        "id": 444521915,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718300114
    },
    {
        "content": "<p>My new errors are actually helpful.   Things I need to correct in domain.xml.     <br>\n[#|2024-06-11T02:46:25.683+0000|WARNING|Payara 6.2023.8|edu.harvard.iq.dataverse.ThumbnailServiceWrapper|_ThreadID=90;_ThreadName=http-thread-pool::jk-connector(4);_TimeMillis=1718073985683;_LevelValue=900;|<br>\n  getDatasetCardImageAsUrl(): Failed to initialize dataset StorageIO for s3://10.5072/FK2/QF48PD (getDataAccessObject: Unsupported storage method.)|#]</p>\n<p>[#|2024-06-11T02:46:25.688+0000|WARNING|Payara 6.2023.8|edu.harvard.iq.dataverse.dataaccess.DataAccess|_ThreadID=90;_ThreadName=http-thread-pool::jk-connector(4);_TimeMillis=1718073985688;_LevelValue=900;|<br>\n  Could not find storage driver for: s3|#]</p>\n<p>[#|2024-06-11T02:46:25.688+0000|WARNING|Payara 6.2023.8|edu.harvard.iq.dataverse.ThumbnailServiceWrapper|_ThreadID=90;_ThreadName=http-thread-pool::jk-connector(4);_TimeMillis=1718073985688;_LevelValue=900;|<br>\n  getDatasetCardImageAsUrl(): Failed to initialize dataset StorageIO for s3://10.5072/FK2/MN0MUZ (getDataAccessObject: Unsupported storage method.)|#]</p>\n<p>[#|2024-06-11T02:46:25.693+0000|WARNING|Payara 6.2023.8|edu.harvard.iq.dataverse.dataaccess.DataAccess|_ThreadID=90;_ThreadName=http-thread-pool::jk-connector(4);_TimeMillis=1718073985693;_LevelValue=900;|<br>\n  Could not find storage driver for: s3|#]</p>\n<p>[#|2024-06-11T02:46:25.693+0000|WARNING|Payara 6.2023.8|edu.harvard.iq.dataverse.ThumbnailServiceWrapper|_ThreadID=90;_ThreadName=http-thread-pool::jk-connector(4);_TimeMillis=1718073985693;_LevelValue=900;|<br>\n  getDatasetCardImageAsUrl(): Failed to initialize dataset StorageIO for s3://10.5072/FK2/KHOWY6 (getDataAccessObject: Ulogs/server.log</p>",
        "id": 444522087,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718300165
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"653479\">jamie jamison</span> <a href=\"#narrow/stream/378866-troubleshooting/topic/Upgrading.205.2E14.20to.206.2E2/near/444521915\">said</a>:</p>\n<blockquote>\n<p>Sorry,  I just realized I posted in the wrong place.  I'm limping through 5.14 to 6.2</p>\n</blockquote>\n<p>No worries, I moved the messages.</p>",
        "id": 444523073,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718300498
    },
    {
        "content": "<p>I'm not sure what some of the domain.xml settings should be so I'm working it out via trail and error.</p>",
        "id": 444524173,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718300888
    },
    {
        "content": "<p>documentation question (<a href=\"https://guides.dataverse.org/en/latest/installation/config.html#second-configure-your-dataverse-installation-to-use-s3-storage\">https://guides.dataverse.org/en/latest/installation/config.html#second-configure-your-dataverse-installation-to-use-s3-storage</a>): <br>\nexample: dataverse.files.storage-driver-id  &lt;id&gt;   Enable &lt;id&gt; as the defaultÂ storageÂ driver.  <code>file</code> (&lt;- default)<br>\nSince all my storage is in s3 buckets, should this be:  Ddataverse.files.storage-driver-id=s3</p>",
        "id": 444526907,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718301808
    },
    {
        "content": "<p>As long as your id is \"s3\", yes. If your id is \"foobar\" it should be \"foobar\".</p>",
        "id": 444527133,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718301869
    },
    {
        "content": "<p>I'm trying to track down storage errors:</p>\n<p>[#|2024-06-11T02:46:25.683+0000|WARNING|Payara 6.2023.8|edu.harvard.iq.dataverse.ThumbnailServiceWrapper|_ThreadID=90;_ThreadName=http-thread-pool::jk-connector(4);_TimeMillis=1718073985683;_LevelValue=900;|<br>\n  getDatasetCardImageAsUrl(): Failed to initialize dataset StorageIO for s3://10.5072/FK2/QF48PD (getDataAccessObject: Unsupported storage method.)|#]</p>\n<p>[#|2024-06-11T02:46:25.688+0000|WARNING|Payara 6.2023.8|edu.harvard.iq.dataverse.dataaccess.DataAccess|_ThreadID=90;_ThreadName=http-thread-pool::jk-connector(4);_TimeMillis=1718073985688;_LevelValue=900;|<br>\n  Could not find storage driver for: s3|#]</p>",
        "id": 444528444,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718302308
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"598112\">@Philip Durbin</span>  <span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> Dataverse doesn't need <code>listBucket</code> but the CLI does, if you want to pull a listing.</p>",
        "id": 444531015,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1718302856
    },
    {
        "content": "<p>Perhaps inaccurately I was using aws cli to check if the buckets were accessable.  <br>\nRight now I'm stuck at the point where payara6 is running but dataverse pages aren't loading.</p>",
        "id": 444531561,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718303026
    },
    {
        "content": "<p>I managed to break the test system to the point it no longer loads.  Since I thought it was  idempotent I tried running the ansible script again.   I stopped and disabled payara6, ran the script and got this message: <br>\nASK [dataverse : fire off installer] <strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><br>\nfatal: [localhost]: FAILED! =&gt; {\"changed\": true, \"cmd\": \"/usr/bin/python3 /tmp/dvinstall/install.py -f --config_file=default.config --noninteractive &gt; /tmp/dvinstall/install.out 2&gt;&amp;1\", \"delta\": \"0:01:26.506903\", \"end\": \"2024-06-13 22:32:09.208629\", \"msg\": \"non-zero return code\", \"rc\": 1, \"start\": \"2024-06-13 22:30:42.701726\", \"stderr\": \"\", \"stderr_lines\": [], \"stdout\": \"\", \"stdout_lines\": []}</p>\n<p>So I realize now it's not idempotent.   I can rebuild from scratch if necessary, had some practice.   But I'm wondering if dropping the dataverse database table would help?</p>",
        "id": 444575647,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718318102
    },
    {
        "content": "<p>To rerun the ansible script: 1) stop and disable payara6, 2) drop (and probably dump) the dvndb, 3) probably doesn't hurt to delete the domain.xml file and then rerun the ansible script.</p>",
        "id": 444585209,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718323992
    },
    {
        "content": "<p>Go go go!</p>",
        "id": 444592752,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718329373
    },
    {
        "content": "<p>Well that was fun while it lasted.Â  Now can't start or restart payara6</p>",
        "id": 444610939,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718339290
    },
    {
        "content": "<p>Anyone out there with postgres experience?<br>\nI was able to reload the dvndb database but I have to set (or reset) the privlidges.  I 'm trying to figure out what  '=Tc/postgres postgres=CTc/postgres dvnuser=CTc/postgres ' so I can add that to dvndb.</p>",
        "id": 444763755,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718389664
    },
    {
        "content": "<p><code>=Tc/postgres</code>? Where are you seeing that?</p>",
        "id": 444764138,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718389803
    },
    {
        "content": "<p>I log into postgres and display the tables<br>\ndvndb      | postgres | UTF8     | C.UTF-8 | C.UTF-8 |<br>\n dvndb_bkup | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =Tc/postgres         +<br>\n            |          |          |         |         | postgres=CTc/postgres+<br>\n            |          |          |         |         | dvnuser=CTc/postgres<br>\n dvndp      | postgres | UTF8     | C.UTF-8 | C.UTF-8 |<br>\n postgres   | postgres | UTF8     | C.UTF-8 | C.UTF-8 |<br>\n template0  | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +<br>\n            |          |          |         |         | postgres=CTc/postgres<br>\n template1  | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +<br>\n            |          |          |         |         | postgres=CTc/postgres<br>\n(6 rows)</p>\n<p>And yes, dvndp is a mispelling error</p>",
        "id": 444764252,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718389845
    },
    {
        "content": "<p><a href=\"/user_uploads/53090/GUVE13_SssbbQoRssg0L_AIF/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/GUVE13_SssbbQoRssg0L_AIF/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/GUVE13_SssbbQoRssg0L_AIF/image.png\"></a></div>",
        "id": 444764369,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718389880
    },
    {
        "content": "<p>Just found Create, connect and temporary (stackexchange)</p>",
        "id": 444764544,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718389928
    },
    {
        "content": "<p>After running ansible it seems you have do drop or rename that initial dvndb, make a new dvndb and then reload,  and the add privlidges.    (By the way did I mention that I lost my sys admin support a week before RHEL7 end-of-life, hense the frantic googling to rebuild on a new system.)</p>",
        "id": 444764980,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718390104
    },
    {
        "content": "<p>I see, like this:</p>\n<div class=\"codehilite\"><pre><span></span><code> dvndb      | postgres | UTF8     | C.UTF-8 | C.UTF-8 |\n dvndb_bkup | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =Tc/postgres         +\n            |          |          |         |         | postgres=CTc/postgres+\n            |          |          |         |         | dvnuser=CTc/postgres\n dvndp      | postgres | UTF8     | C.UTF-8 | C.UTF-8 |\n postgres   | postgres | UTF8     | C.UTF-8 | C.UTF-8 |\n template0  | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +\n            |          |          |         |         | postgres=CTc/postgres\n template1  | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +\n            |          |          |         |         | postgres=CTc/postgres\n(6 rows)\n</code></pre></div>\n<p>I'm using fenced code blocks above. Very useful here in <a href=\"https://zulip.com/help/code-blocks\">Zulip</a> and in <a href=\"https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks\">GitHub</a>. You could try this if you want:</p>\n<div class=\"codehilite\"><pre><span></span><code>```\ntest\n```\n</code></pre></div>",
        "id": 444765300,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718390227
    },
    {
        "content": "<p>But yeah, I'm not familiar with <code>=Tc/postgres</code>.</p>",
        "id": 444765604,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718390340
    },
    {
        "content": "<p>Check this out: <a href=\"https://www.postgresql.org/docs/current/ddl-priv.html#PRIVILEGE-ABBREVS-TABLE\">https://www.postgresql.org/docs/current/ddl-priv.html#PRIVILEGE-ABBREVS-TABLE</a></p>",
        "id": 444765716,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718390389
    },
    {
        "content": "<p>and <a href=\"https://dba.stackexchange.com/questions/264441/is-my-database-secure-what-does-tc-postgres-allow/264445#264445\">https://dba.stackexchange.com/questions/264441/is-my-database-secure-what-does-tc-postgres-allow/264445#264445</a> seem to say the same thing, that \"T\" is for TEMPORARY and \"c\" is for CONNECT.</p>",
        "id": 444766009,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718390487
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> IIRC postgres ownership and privileges may need to be modified table-by-table</p>",
        "id": 444767483,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1718391007
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> if you dump and import as Phil suggests you can use the <code>-O</code> (no \"owner\") flag which may greatly simplify the process?</p>",
        "id": 444767620,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1718391057
    },
    {
        "content": "<p>That makes rebuilding the database a bit more daunting   I'll go back and try that - dump from the previous test system and bring over to new.</p>",
        "id": 444767700,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718391086
    },
    {
        "content": "<p>Dropped the database and reloaded from  a dump.  It now matches up to what the old server postgres looked like  but still not getting the dataverse front page.  May take waiting longer</p>",
        "id": 444778361,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718395088
    },
    {
        "content": "<p>Anything at the equivalent of <a href=\"https://demo.dataverse.org/api/info/version\">https://demo.dataverse.org/api/info/version</a> ?</p>",
        "id": 444778790,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718395252
    },
    {
        "content": "<p>I'll try that as soon as I can get payara6 to start again</p>",
        "id": 444779034,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718395351
    },
    {
        "content": "<p>404 page not found, requested service not available</p>",
        "id": 444779358,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718395467
    },
    {
        "content": "<p>any errors in server.log?</p>",
        "id": 444779715,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718395592
    },
    {
        "content": "<p>But I do get the payara page</p>",
        "id": 444782332,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718396533
    },
    {
        "content": "<p>I'm digging in the server log now</p>",
        "id": 444782363,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718396544
    },
    {
        "content": "<p>[#|2024-06-14T00:19:37.128+0000|SEVERE|Payara 6.2023.8|edu.harvard.iq.dataverse.mydata.DataRetrieverAPI|_ThreadID=90;_ThreadName=http-thread-pool::jk-connector(5);_TimeMillis=1718324377128;_LevelValue=1000;|<br>\n  Sorry, nothing was found for these roles: Admin, File Downloader, Dataverse + Dataset Creator, Dataverse Creator, Dataset Creator, Contributor, Curator, Member|#]</p>",
        "id": 444782720,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718396667
    },
    {
        "content": "<p>Looks like the database is messed up somehow</p>",
        "id": 444782749,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718396681
    },
    {
        "content": "<p>Huh. Yeah, sounds like it. <span aria-label=\"disappointed\" class=\"emoji emoji-1f61e\" role=\"img\" title=\"disappointed\">:disappointed:</span></p>",
        "id": 444784758,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718397305
    },
    {
        "content": "<p>There has to be a way to reload or restore a database</p>",
        "id": 444784853,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718397341
    },
    {
        "content": "<p>I mean, a long time ago I used scripts like this to dump and restore:</p>\n<ul>\n<li><a href=\"https://github.com/IQSS/dataverse/blob/v6.2/scripts/database/homebrew/dump\">https://github.com/IQSS/dataverse/blob/v6.2/scripts/database/homebrew/dump</a></li>\n<li><a href=\"https://github.com/IQSS/dataverse/blob/v6.2/scripts/database/homebrew/restore\">https://github.com/IQSS/dataverse/blob/v6.2/scripts/database/homebrew/restore</a></li>\n</ul>\n<p>10 years ago according to git. But something like that should work, I would think.</p>",
        "id": 444785822,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718397685
    },
    {
        "content": "<p>that looks like what I did (will paste the commands in)</p>",
        "id": 444786032,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718397766
    },
    {
        "content": "<p>It looks like <span class=\"user-mention\" data-user-id=\"598843\">@Deirdre Kirmis</span> has experience with database backup and recovery: <a href=\"https://groups.google.com/g/dataverse-community/c/kTEUkxHB_ZM/m/T6aRZ9SpCwAJ\">https://groups.google.com/g/dataverse-community/c/kTEUkxHB_ZM/m/T6aRZ9SpCwAJ</a></p>",
        "id": 444786243,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1718397864
    },
    {
        "content": "<p>Ok,  this is probably not an official way to fix things but after reloading the database I reran ansible and now the test looks ok.<br>\nAt that point I did as <span class=\"user-mention\" data-user-id=\"598112\">@Philip Durbin</span>  suggested and ran with \"/api/info/version\" and got status 'ok' and version '6.2'</p>",
        "id": 444786935,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718398140
    },
    {
        "content": "<p>Is it possible that rerunning the ansible script fixed the missing roles?</p>",
        "id": 444787089,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718398198
    },
    {
        "content": "<p>I that I'm following the directions exactly from <a href=\"https://guides.dataverse.org/en/latest/installation/config.html#second-configure-your-dataverse-installation-to-use-s3-storage\">https://guides.dataverse.org/en/latest/installation/config.html#second-configure-your-dataverse-installation-to-use-s3-storage</a></p>\n<p>Example :<br>\n&lt;jvm-options&gt;-Ddataverse.files.storage-driver-id=file&lt;/jvm-options&gt;<br>\n        &lt;jvm-options&gt;-Xmx3841m&lt;/jvm-options&gt;<br>\n        &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.type=s3&lt;/jvm-options&gt;<br>\n        &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.label=dataverse-test-oregon&lt;/jvm-options&gt;<br>\n        &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.type=s3&lt;/jvm-options&gt;<br>\n        &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon=dataverse-test-oregon&lt;/jvm-options&gt;<br>\n        &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.download-redirect=true&lt;/jvm-options&gt;<br>\n        &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.upload-redirect=true&lt;/jvm-options&gt;</p>\n<p>If I restart and check status of payar6 I get:<br>\nsudo systemctl status payara6<br>\nÃ— payara6.service - Payara Server<br>\n     Loaded: loaded (/etc/systemd/system/payara6.service; enabled; preset: disabled)<br>\n     Active: failed (Result: exit-code) since Mon 2024-06-17 17:07:10 UTC; 8min ago<br>\n    Process: 43806 ExecStart=/usr/bin/java -jar /usr/local/payara6/glassfish/lib/client/appserver-cli.jar start-domain (code=exited, status=1/FAILURE)<br>\n        CPU: 2.396s</p>\n<p>Jun 17 17:07:08 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: Starting Payara Server...<br>\nJun 17 17:07:10 ip-172-31-23-165.us-west-2.compute.internal java[43806]: Port 7676 is in use<br>\nJun 17 17:07:10 ip-172-31-23-165.us-west-2.compute.internal java[43806]: Command start-domain failed.<br>\nJun 17 17:07:10 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: payara6.service: Control process exited, code=exited, status=1/FAILURE<br>\nJun 17 17:07:10 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: payara6.service: Failed with result 'exit-code'.<br>\nJun 17 17:07:10 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: Failed to start Payara Server.<br>\nJun 17 17:07:10 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: payara6.service: Consumed 2.396s CPU time.<br>\n[rocky@ip-172-31-23-165 ~]$</p>\n<p>And, oddly the test system looks like it's up,  though with no buckets until I reboot the system then I get a 500</p>",
        "id": 445184642,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718644711
    },
    {
        "content": "<p>And another question.  When it's up  I'm not able to log into the test dataverse with the default admin account.   In the ansible script it looks like the admin account is 'dataverseAdmin' and thepassword is \"admin1\"  which gets the error \"username, email address, or password you entered is invalid.\"</p>",
        "id": 445211004,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718653311
    },
    {
        "content": "<p>And for shibboleth,  following <a href=\"https://guides.dataverse.org/en/latest/installation/shibboleth.html#install-shibboleth-via-yum\">https://guides.dataverse.org/en/latest/installation/shibboleth.html#install-shibboleth-via-yum</a><br>\nI'm stuck at the error:   Error: GPG check FAILED</p>",
        "id": 445213589,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718654243
    },
    {
        "content": "<p>is there anything more descriptive in the Payara server.log?<br>\non Shibboleth: worst case you can set gpg_enable=0 in the repo config, but better to import the GPG key</p>",
        "id": 445375759,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1718721609
    },
    {
        "content": "<p>For the payara server log part of the problem is I'm not sure what to look for.  I'm partially relying on the time stamp.<br>\nFor shib I'm obviously not importing the GPG correctly.     I have back-to-back patron consults till noon and then will dig back in.</p>",
        "id": 445390351,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718724667
    },
    {
        "content": "<p>my shibboleth.repo is looking at</p>\n<div class=\"codehilite\"><pre><span></span><code>gpgkey=https://shibboleth.net/downloads/service-provider/RPMS/repomd.xml.key\nhttps://shibboleth.net/downloads/service-provider/RPMS/cantor.repomd.xml.key\n</code></pre></div>",
        "id": 445434564,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1718736279
    },
    {
        "content": "<p>That is the same thing that I have:<br>\n**</p>\n<p>[shibboleth]<br>\nname=Shibboleth (rockylinux9)</p>\n<h1>Please report any problems to <a href=\"https://shibboleth.atlassian.net/jira\">https://shibboleth.atlassian.net/jira</a></h1>\n<p>type=rpm-md<br>\nmirrorlist=https://shibboleth.net/cgi-bin/mirrorlist.cgi/rockylinux9<br>\ngpgcheck=1<br>\ngpgkey=https://shibboleth.net/downloads/service-provider/RPMS/repomd.xml.key<br>\n<a href=\"https://shibboleth.net/downloads/service-provider/RPMS/cantor.repomd.xml.key\">https://shibboleth.net/downloads/service-provider/RPMS/cantor.repomd.xml.key</a><br>\nenabled=1<br>\n**</p>",
        "id": 445438383,
        "sender_full_name": "jamie jamison",
        "timestamp": 1718737477
    },
    {
        "content": "<p>One thing I am running into is that out-of-the-box I can't log into Dataverse. I've tried to unblock admin in the main.yml script but that didn't help.<br>\nIs there a way via the api to change the dataverseAdmin password?  I'm reading through the documenation but havent found that yet</p>",
        "id": 446684134,
        "sender_full_name": "jamie jamison",
        "timestamp": 1719253060
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> if you're using Dataverse-Ansible you can set it as a group_var?</p>",
        "id": 446702863,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1719258516
    },
    {
        "content": "<p>Ok, I'll look into that. I did try setting the dataverseAdmin password in the ansible script.</p>\n<p>Other thing: even before I try to add s3 buckets I get this:<br>\n<strong>exception</strong></p>\n<p>jakarta.servlet.ServletException: /dataset.xhtml @595,164 rendered=\"#{settingsWrapper.makeDataCountDisplayEnabled and DatasetPage.doi}\": The class 'edu.harvard.iq.dataverse.DatasetPage' does not have the property 'doi'.<br>\n<strong>root cause</strong></p>\n<p>jakarta.el.PropertyNotFoundException: /dataset.xhtml @595,164 rendered=\"#{settingsWrapper.makeDataCountDisplayEnabled and DatasetPage.doi}\": The class 'edu.harvard.iq.dataverse.DatasetPage' does not have the property 'doi'.</p>\n<p>I'm wondering where makeDataCount is enabled - trying to find in main.yml</p>",
        "id": 446706689,
        "sender_full_name": "jamie jamison",
        "timestamp": 1719259774
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> I don't think Ansible knows about MDC yet?</p>",
        "id": 446906643,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1719327169
    },
    {
        "content": "<p>Ok,  mostly I'm trying to understand the error messages - lot of this is new to me so I'm still limping up the learning curve</p>",
        "id": 446933082,
        "sender_full_name": "jamie jamison",
        "timestamp": 1719332806
    },
    {
        "content": "<p>Since I'm using a reloaded dvndb database (from the REHL7 test dataverse)  I'm wondering if it's possilbe that MDC is in the database and causing that error.</p>",
        "id": 446933821,
        "sender_full_name": "jamie jamison",
        "timestamp": 1719332964
    },
    {
        "content": "<p>And I may have found something in 6.2 documentaation - <a href=\"https://guides.dataverse.org/en/latest/admin/make-data-count.html#enable-or-disable-display-of-make-data-count-metrics\">https://guides.dataverse.org/en/latest/admin/make-data-count.html#enable-or-disable-display-of-make-data-count-metrics</a></p>\n<p>And that seems to solve at least that error.   I'm putting that in my notes - things to consider when restoring a pervious database</p>",
        "id": 446934839,
        "sender_full_name": "jamie jamison",
        "timestamp": 1719333199
    },
    {
        "content": "<p>Actually the most exasperating issue at this point is that the default, out-of-the-box  dataverseAdmin password doesn't work though this might also be because of the reloaded dvdnb database.  Is that where passwords are stored?</p>",
        "id": 446990768,
        "sender_full_name": "jamie jamison",
        "timestamp": 1719348087
    },
    {
        "content": "<p>Also, sometimes payara6 seems 'stuck'.  Unable to stop or restart or even kill the process.</p>\n<p>payara6.service - Payara Server<br>\n     Loaded: loaded (/etc/systemd/system/payara6.service; enabled; preset: disabled)<br>\n     Active: failed (Result: exit-code) since Wed 2024-06-26 17:43:43 UTC; 39min ago<br>\n    Process: 720 ExecStart=/usr/bin/java -jar /usr/local/payara6/glassfish/lib/client/appserver-cli.jar start-domain (code=exited, st&gt;<br>\n        CPU: 1.304s</p>\n<p>Jun 26 17:43:38 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: Starting Payara Server...<br>\nJun 26 17:43:43 ip-172-31-23-165.us-west-2.compute.internal java[720]: com.sun.enterprise.universal.xml.MiniXmlParserException: \"Xml &gt;<br>\nJun 26 17:43:43 ip-172-31-23-165.us-west-2.compute.internal java[720]: Message: elementGetText() function expects text only elment bu&gt;<br>\nJun 26 17:43:43 ip-172-31-23-165.us-west-2.compute.internal java[720]: Command start-domain failed.<br>\nJun 26 17:43:43 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: payara6.service: Control process exited, code=exited, status=&gt;<br>\nJun 26 17:43:43 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: payara6.service: Failed with result 'exit-code'.<br>\nJun 26 17:43:43 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: Failed to start Payara Server.<br>\nJun 26 17:43:43 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: payara6.service: Consumed 1.304s CPU time.<br>\n[rocky@ip-172-31-23-165 logs]$</p>",
        "id": 447296906,
        "sender_full_name": "jamie jamison",
        "timestamp": 1719426392
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> I've seen Payara do this on <a href=\"http://beta.dataverse.org\">beta.dataverse.org</a> - is there more information in server.log? on dataverseAdmin - since you have access to the DB, you could update the e-mail address associated with userid '1' in the authenticateuser table and trigger a password reset, or you could just blank the password entry?</p>",
        "id": 447523107,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1719506497
    },
    {
        "content": "<p>on restoring databases / moving servers: I keep a shell script around on test machines, <a href=\"http://reset_settings.sh\">reset_settings.sh</a> or some such, with a list of commonly-required curl commands to make the test server a test server when I've imported a copy of the production database</p>",
        "id": 447523331,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1719506564
    },
    {
        "content": "<p>And they problem turned out to be a typo by me.   Now back on track. </p>\n<p>The current s3 bucket related error is:<br>\n6.2023.8|edu.harvard.iq.dataverse.dataaccess.DataAccess|_ThreadID=88;_ThreadName=http-thread-pool::jk-connector(2);_TimeMillis=1719511203190;_LevelValue=900;|<br>\nÂ Â Could not find storage driver for: s3|#]</p>\n<p>Lastly, I can't seem to wget the <a href=\"http://reset_settings.sh\">reset_settings.sh</a> file.  Is there another place to get it?</p>",
        "id": 447556412,
        "sender_full_name": "jamie jamison",
        "timestamp": 1719514339
    },
    {
        "content": "<p>About the storage driver issue,  here is part of the domain.xml code:</p>\n<p>&lt;jvm-options&gt;-Ddataverse.files.storage-driver-id=s3&lt;/jvm-options&gt;  &lt;- is this correct,  the default is 'file' but should it be changed to 's3' for the s3 buckets?</p>\n<div class=\"codehilite\"><pre><span></span><code>    &lt;jvm-options&gt;-Xmx3841m&lt;/jvm-options&gt;\n    &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.type=s3&lt;/jvm-options&gt;\n    &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.label=dataverse-test-oregon&lt;/jvm-options&gt;\n    &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.bucket-name=dataverse-test-oregon&lt;/jvm-options&gt;\n    &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.download-redirect=true&lt;/jvm-options&gt;\n    &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.upload-redirect=true&lt;/jvm-options&gt;\n</code></pre></div>",
        "id": 447604034,
        "sender_full_name": "jamie jamison",
        "timestamp": 1719527491
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> the script was just something I threw together to make a copy of my production database suitable for our test server. I'm happy to share mine with you (just some API calls to change settings). if you're all S3, then yes you want <code>storage-driver-id=s3</code>.  it may be because your label is dataverse-test-oregon instead of s3?</p>",
        "id": 448375805,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1719850235
    },
    {
        "content": "<p>This is what I'm a bit confused about.   According to the documentation:<br>\ndataverse.files.&lt;id&gt;.label&lt;?&gt;  <strong>Required</strong>Â label to be shown in the UI for thisÂ storage  default (none)</p>\n<p>So is it correct that the label is what's shown in the UI wouldn't the lable be 'dataverse-test-oregon'?</p>",
        "id": 448407331,
        "sender_full_name": "jamie jamison",
        "timestamp": 1719858764
    },
    {
        "content": "<p>Did you figure it out, what's shown in the UI? (I'm not sure, myself.)</p>",
        "id": 448901324,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720025147
    },
    {
        "content": "<p>we're still working on it.  Fresh install with reloaded database is messier then fresh install.  You guys get the notes on how we did it when done.</p>",
        "id": 448902924,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720025708
    },
    {
        "content": "<p>Great, much appreciated. Good luck!</p>",
        "id": 448903159,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720025786
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> the label appears to be a friendly name, the <code>&lt;id&gt;</code> value identifies the datastore. does that make sense?</p>",
        "id": 449366959,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1720202136
    },
    {
        "content": "<p>In my case probably not.   I understand the label. For the test I'm using the bucket name as the friendly name. For the &lt;id&gt; I guess that's were I'm confused.     If the default is 'file' for local files system, what is appropriate for s3 storage?</p>\n<p>Documentation:<br>\ndataverse.files.storage-driver-id &lt;id&gt; Enable &lt;id&gt; as the defaultÂ storageÂ driver. <code>file</code></p>",
        "id": 449376071,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720205241
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> the &lt;id&gt; bit threw me as well, our is simply \"s3\" and suits us for now. i'll need to get more descriptive as we add datastores.</p>",
        "id": 450162139,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1720529057
    },
    {
        "content": "<p>Ok.   Right now dataverse 6.2 is dead in the water becuase it can't access the s3 buckets and 5.14 is giving me grief since the operating system is end-of-life.</p>",
        "id": 450236880,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720546281
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> remind me of the error you get accessing the buckets from 6.2?</p>",
        "id": 450261850,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1720552663
    },
    {
        "content": "<p>jamie jamison:Â And they problem turned out to be a typo by me. Now back on track.</p>\n<p>The current s3 bucket related error is:<br>\n6.2023.8|edu.harvard.iq.dataverse.dataaccess.DataAccess|_ThreadID=88;_ThreadName=http-thread-pool::jk-connector(2);_TimeMillis=1719511203190;_LevelValue=900;|<br>\nÂ Â Could not find storage driver for: s3|#]</p>\n<p>Lastly, I can't seem to wget theÂ <a href=\"http://reset_settings.sh/\">reset_settings.sh</a>Â file. Is there another place to get it?</p>\n<p>jamie jamison:Â About the storage driver issue, here is part of the domain.xml code:</p>\n<p>&lt;jvm-options&gt;-Ddataverse.files.storage-driver-id=s3&lt;/jvm-options&gt; &lt;- is this correct, the default is 'file' but should it be changed to 's3' for the s3 buckets?</p>\n<div class=\"codehilite\"><pre><span></span><code>    &lt;jvm-options&gt;-Xmx3841m&lt;/jvm-options&gt;\n    &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.type=s3&lt;/jvm-options&gt;\n    &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.label=dataverse-test-oregon&lt;/jvm-options&gt;\n    &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.bucket-name=dataverse-test-oregon&lt;/jvm-options&gt;\n    &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.download-redirect=true&lt;/jvm-options&gt;\n    &lt;jvm-options&gt;-Ddataverse.files.dataverse-test-orego\nn.upload-redirect=true&lt;/jvm-options&gt;\n</code></pre></div>",
        "id": 450263012,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720552925
    },
    {
        "content": "<p>I'm glad fixing the typo is helping!</p>",
        "id": 450266955,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720554210
    },
    {
        "content": "<p>Sorry, a reset settings script? I'm not familiar with it. You're seeing this in the guides or a release note somewhere?</p>",
        "id": 450267021,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720554236
    },
    {
        "content": "<p>reset settings script was a suggestion from Don.  Not in the guides or release notes.   <br>\nSo far still can't access the s3 buckets and unable to get letsencrypt working.</p>",
        "id": 450504733,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720629219
    },
    {
        "content": "<p>Oh, I understand now, thanks</p>",
        "id": 450508321,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720630480
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> in this case your storage-driver-id for s3 is <code>dataverse-test-oregon</code></p>",
        "id": 450550455,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1720641420
    },
    {
        "content": "<p>the reset settings script is just a handful of curl commands I threw together in a script to set the Authority of our test server instead of our production, use the throw-away shoulder, and put up a banner warning that the test server is just a test server. it's really a way to automate the stuff I had to manually fix each time I imported a copy of our production database.</p>",
        "id": 450550775,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1720641520
    },
    {
        "content": "<p>I guess I didn't completely understand the documentation.  Right now test is down due while trying to get letsencrypt working.   But as soon as it's back I'll try that.  Clarification helpful</p>",
        "id": 450550805,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720641529
    },
    {
        "content": "<p>This is aside from the installation problem.  Since Dataverse 5.14 on RedHat7 is barely working or staying up I've found I can still publish some of the user datasets with the API - so they can get DOIs for publishing.  API works great.</p>",
        "id": 450610160,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720665950
    },
    {
        "content": "<p>I anyone else having issues with 'stuck' payara6.  Service can't be stopped, restarted or killed.<br>\nsudo systemctl status payara6<br>\nÃ— payara6.service - Payara Server<br>\n     Loaded: loaded (/etc/systemd/system/payara6.service; enabled; preset: disabled)<br>\n     Active: failed (Result: timeout) since Tue 2024-07-09 17:49:42 UTC; 2 days ago<br>\n        CPU: 28.414s</p>\n<p>Jul 09 17:47:41 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: Starting Payara Server...<br>\nJul 09 17:49:41 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: payara6.service: start operation timed out. Terminating.<br>\nJul 09 17:49:42 ip-172-31-23-165.us-west-2.compute.internal java[728]: Waiting for domain1 to start .............................&gt;<br>\nJul 09 17:49:42 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: payara6.service: Control process exited, code=exited, sta&gt;<br>\nJul 09 17:49:42 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: payara6.service: Failed with result 'timeout'.<br>\nJul 09 17:49:42 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: Failed to start Payara Server.<br>\nJul 09 17:49:42 ip-172-31-23-165.us-west-2.compute.internal systemd[1]: payara6.service: Consumed 28.414s CPU time.<br>\nlines 1-12/12 (END)</p>",
        "id": 450818475,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720734522
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"626369\">Don Sizemore</span> <a href=\"#narrow/stream/378866-troubleshooting/topic/Upgrading.205.2E14.20to.206.2E2/near/450550455\">said</a>:</p>\n<blockquote>\n<p><span class=\"user-mention silent\" data-user-id=\"653479\">jamie jamison</span> in this case your storage-driver-id for s3 is <code>dataverse-test-oregon</code></p>\n</blockquote>\n<p>I think I need one more clarification.  If there are 4 s3 buckets, bucket1, bucket2, bucket3, bucket4.  Does each one have to have it's own storage-driver-id?<br>\ndataverse.files.bucket1-storage-driver-id=bucket1<br>\ndataverse.files.bucket2-storage-driver-id=bucket2<br>\ndataverse.files.bucket3-storage-driver-id=bucket3<br>\ndataverse.files.bucket4-storage-driver-id=bucket4</p>",
        "id": 450847073,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720747555
    },
    {
        "content": "<p>These options are all mixed up.  The <code>&lt;id&gt;</code> part needs to be a unique indentifier for your storage, the <code>storage-driver-id</code> <em>option</em> (mind the \".\") references the driver to use for storage <em>&lt;id&gt;</em>.</p>\n<p>Here's a complete example of an S3 storage from our beta env:</p>\n<div class=\"codehilite\"><pre><span></span><code>dataverse.files.s3.bucket-name=juelich_data_beta\ndataverse.files.s3.custom-endpoint-url=https://s3.fz-juelich.de\ndataverse.files.s3.label=JÃ¼lich-DATA-Object-Store\ndataverse.files.s3.path-style-access=true\ndataverse.files.s3.type=s3\ndataverse.files.storage-driver-id=s3\n</code></pre></div>\n<p>So in your case, this needs to be (assuming all of them are S3):</p>\n<div class=\"codehilite\"><pre><span></span><code>dataverse.files.bucket1.storage-driver-id=s3\ndataverse.files.bucket1.s3.xxx\n...\ndataverse.files.bucket2.storage-driver-id=s3\ndataverse.files.bucket2.s3.xxx\n...\ndataverse.files.bucket3.storage-driver-id=s3\ndataverse.files.bucket3.s3.xxx\n...\ndataverse.files.bucket4.storage-driver-id=s3\ndataverse.files.bucket4.s3.xxx\n...\n</code></pre></div>",
        "id": 450895535,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1720768724
    },
    {
        "content": "<p>The docs say \"dataverse.files.storage-driver-id\" allows you to \"Enable &lt;id&gt; as the default storage driver.\" -- <a href=\"https://guides.dataverse.org/en/6.3/installation/config.html#list-of-s3-storage-options\">https://guides.dataverse.org/en/6.3/installation/config.html#list-of-s3-storage-options</a></p>\n<p>So you'll want to pick one of your four buckets as the &lt;id&gt;, like this:</p>\n<p>dataverse.files.storage-driver-id=bucket3</p>",
        "id": 450992786,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720794597
    },
    {
        "content": "<p>Dang you're right! I mixed that up myself! See, it's fricking complicated!</p>",
        "id": 451002744,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1720796667
    },
    {
        "content": "<p>One day I will make the MPCONFIG part for the storage system and take care to rename the default driver option!</p>",
        "id": 451002841,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1720796693
    },
    {
        "content": "<p>So friggin' complicated. Need more docs, I guess, short term.</p>",
        "id": 451004964,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720797082
    },
    {
        "content": "<p>I'll make an example along with the ntoes I send you.   Last question to clarify.  You only need 1 default-driver-id?  Even with 2 or more s3 buckets?</p>",
        "id": 451020707,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720800940
    },
    {
        "content": "<p>Yes. That's the driver that will be assigned to a new collection if you don't specify a different one.</p>",
        "id": 451038053,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1720806370
    },
    {
        "content": "<p>There's only 1 instance wide default :-)</p>",
        "id": 451038091,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1720806390
    },
    {
        "content": "<p>Thank you for clarifying.   I'll send over my example as soon as I get finished setting up the new server.</p>",
        "id": 451038240,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720806446
    },
    {
        "content": "<p>Hereis some code following the example:<br>\n&lt;jvm-options&gt;-**Ddataverse.files.datavers-test-oregon.storage-driver-id=s3&lt;/jvm-options&gt;<br>\n&lt;jvm-options&gt;-Ddataverse.files.dataverese-test-oregon.type=s3&lt;/jvm-options&gt;<br>\n&lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon=dataverse-test-oregon&lt;/jvm-options&gt;<br>\n&lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.download-redirect=true&lt;/jvm-o**ptions&gt;<br>\n&lt;jvm-options&gt;-Ddataverse.files.dataverse-test-oregon.upload-redirect=true&lt;/jvm-options&gt;</p>\n<p>&lt;jvm-options&gt;-<strong>Ddataverse.files.ssda-files.storage-driver-id=s3</strong>&lt;/jvm-options&gt;<br>\n&lt;jvm-options&gt;-Ddataverse.files.ssda-files.type=s3&lt;/jvm-options&gt;<br>\n&lt;jvm-options&gt;-Ddataverse.files.ssda-files=ssda-files&lt;/jvm-options&gt;<br>\n&lt;jvm-options&gt;-Ddataverse.files.ssda-files.download-redirect=true&lt;/jvm-options&gt;<br>\n&lt;jvm-options&gt;-Ddataverse.files.ssda-files.upload-redirect=true&lt;/jvm-options&gt;</p>\n<p>and I still get:<br>\n[#|2024-07-12T20:14:08.003+0000|WARNING|Payara 6.2023.8|edu.harvard.iq.dataverse.dataaccess.DataAccess|_ThreadID=88;_ThreadName=http-thread-pool::jk-connector(3);_TimeMillis=1720815248003;_LevelValue=900;|<br>\n  Could not find storage driver for: s3|#]</p>\n<p>[#|2024-07-12T20:14:08.003+0000|WARNING|Payara 6.2023.8|edu.harvard.iq.dataverse.ThumbnailServiceWrapper|_ThreadID=88;_ThreadName=http-thread-pool::jk-connector(3);_TimeMillis=1720815248003;_LevelValue=900;|<br>\n  getDatasetCardImageAsUrl(): Failed to initialize dataset StorageIO for s3://10.5072/FK2/MN0MUZ (getDataAccessObject: Unsupported storage method.)|#]</p>\n<p>[#|2024-07-12T20:14:08.008+0000|WARNING|Payara 6.2023.8|edu.harvard.iq.dataverse.dataaccess.DataAccess|_ThreadID=88;_ThreadName=http-thread-pool::jk-connector(3);_TimeMillis=1720815248008;_LevelValue=900;|<br>\n  Could not find storage driver for: s3|#]</p>\n<p>[#|2024-07-12T20:14:08.009+0000|WARNING|Payara 6.2023.8|edu.harvard.iq.dataverse.ThumbnailServiceWrapper|_ThreadID=88;_ThreadName=http-thread-pool::jk-connector(3);_TimeMillis=1720815248009;_LevelValue=900;|<br>\n  getDatasetCardImageAsUrl(): Failed to initialize dataset StorageIO for s3://10.5072/FK2/KHOWY6 (getDataAccessObject: Unsupported storage method.)|#]</p>\n<p>So maybe the problem is something else? I did check the aws configuration and that looks correct.</p>",
        "id": 451073779,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720817696
    },
    {
        "content": "<p><code>dataverse.files.datavers-test-oregon.storage-driver-id=s3</code> has a typo it it. An \"e\" is missing from the end of \"dataverse\".</p>",
        "id": 451074527,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720818029
    },
    {
        "content": "<p>well that embarrassing for an old secretary...   Will go retry now</p>",
        "id": 451074594,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720818063
    },
    {
        "content": "<p>Personally, I would use and <code>&lt;id&gt;</code> that doesn't have hyphens it in. But maybe they do work. Dunno.</p>",
        "id": 451074616,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720818072
    },
    {
        "content": "<p>I fixed the typo.  Still get the error.  The reason I formatted the way that I did was an example from Oliver Bertuch (above):<br>\ndataverse.files.bucket4.storage-driver-id=s3</p>\n<p>and this is what's in documentation:<br>\ndataverse.files.storage-driver-id  &lt;id&gt;  Enable &lt;id&gt; as the defaultÂ storageÂ driver. <code>file</code></p>",
        "id": 451075924,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720818596
    },
    {
        "content": "<p>I feel like there's something amiss with your config but it's late here. Maybe I can look at it with fresh eyes next week.</p>",
        "id": 451078585,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720819793
    },
    {
        "content": "<p>There's also the missing .label thing</p>",
        "id": 451078779,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1720819872
    },
    {
        "content": "<p>Educated guess on the error messages: the storage driver ID is IIRC built into the location URL. So there is no storage driver called \"s3\" around as per the config you posted</p>",
        "id": 451078899,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1720819927
    },
    {
        "content": "<p>Yupp. These storage id's need to be migrated... (DataAccess.getStorageIdFromLocation)</p>",
        "id": 451079217,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1720820065
    },
    {
        "content": "<p>Or you configure a storage driver that has an id \"s3\" <span aria-label=\"wink\" class=\"emoji emoji-1f609\" role=\"img\" title=\"wink\">:wink:</span></p>",
        "id": 451079320,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1720820136
    },
    {
        "content": "<p>Could you post a sample of what that looks like? I've been using this example:<br>\ndataverse.files.bucket2.storage-driver-id=s3</p>",
        "id": 451081806,
        "sender_full_name": "jamie jamison",
        "timestamp": 1720821042
    },
    {
        "content": "<p>Related: <a href=\"https://github.com/IQSS/dataverse/issues/10684\">https://github.com/IQSS/dataverse/issues/10684</a></p>",
        "id": 451387353,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1720997580
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> this one doesn't look right, for example:</p>\n<div class=\"codehilite\"><pre><span></span><code>&lt;jvm-options&gt;-Ddataverse.files.ssda-files=ssda-files&lt;/jvm-options&gt;\n</code></pre></div>\n<p><code>ssda-files</code> is your <code>&lt;id&gt;</code> and there should be something after it like <code>.type</code> or <code>.label</code> or whatever.</p>",
        "id": 451508551,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1721052457
    },
    {
        "content": "<p>Another non-s3 question.  We still having trouble with the install.  I was asked what branch we should be using if we want to install dataverse 6.2 on rocky 9.  On going issues with letsencrypt.<br>\nShould we use 243_rocky_9 or 6.2?</p>",
        "id": 451645336,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721084305
    },
    {
        "content": "<p>Thanks @jamie, if we would like to use the community ansible scripts for dvn 6.2 on rocky 9, what is the suggested branch to use?<br>\n<a href=\"https://github.com/gdcc/dataverse-ansible/tree/v6.2\">https://github.com/gdcc/dataverse-ansible/tree/v6.2</a> or<br>\n<a href=\"https://github.com/gdcc/dataverse-ansible/tree/243_rocky_9\">https://github.com/gdcc/dataverse-ansible/tree/243_rocky_9</a></p>",
        "id": 451645665,
        "sender_full_name": "Kristian Allen - UCLA",
        "timestamp": 1721084438
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"736518\">@Kristian Allen - UCLA</span> is this a new installation? Typically that's what the Ansible scripts are used for.</p>",
        "id": 451760378,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1721136906
    },
    {
        "content": "<p>Yes,  we are doing a fresh install because we were unable to update RHEL7 in-place.  So  we are doing a fresh install of 6.2 on Rocky 9</p>",
        "id": 451808490,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721148779
    },
    {
        "content": "<p>Right, right. I don't want to tell you the wrong thing. Better wait for <span class=\"user-mention\" data-user-id=\"626369\">@Don Sizemore</span></p>",
        "id": 451808963,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1721148966
    },
    {
        "content": "<p>yes <span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> is right -- clean install. We've been using v6.2 branch but been having a few issues , we'll submit some PRs once things settle down and we get things working. </p>\n<p>The current blocker is multiple processes grabbing the same port:</p>\n<ul>\n<li>Cannot define multiple Listeners on the same IP:port\\n\\n</li>\n<li>Error while running systemctl restart httpd.\\n\\nJob for httpd.service failed because the control process exited with error code</li>\n<li>AH00526: Syntax error on line 5 of /etc/httpd/conf.d/ssl.conf</li>\n</ul>\n<p>Following the readme, we updated the <code>main.yml</code> </p>\n<div class=\"codehilite\"><pre><span></span><code>apache:\n  enabled: true\n  public_fqdn:\n  ssl:\n    enabled: false\n    remote_cert: false\n    port: 443\n    cert:\n    interm:\n    key:\n    pem:\n      cert:\n      key:\n      interm:\n  port: 80\n</code></pre></div>\n<p>But is 443 or 80 redefined anywhere, like in <code>dataverse-apache.yml</code>?</p>\n<div class=\"codehilite\"><pre><span></span><code>- name: certbot bonks on listen 443\n  lineinfile:\n    path: &#39;{{ apache_virtualhost_dir }}/http.proxy.conf&#39;\n    regexp: &#39;^Listen 443 https&#39;\n    state: absent\n  when: letsencrypt.enabled == true\n</code></pre></div>",
        "id": 451810423,
        "sender_full_name": "Kristian Allen - UCLA",
        "timestamp": 1721149450
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"736518\">@Kristian Allen - UCLA</span> the Apache proxy bits of Dataverse-Ansible are very, very untested. pull requests to fix problems or specific issue descriptions are most welcome.</p>",
        "id": 451813727,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1721150266
    },
    {
        "content": "<p>Well we're definately testing them at ucla</p>",
        "id": 451824072,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721153014
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"626369\">@Don Sizemore</span>  We're wondering if we are using the correct branch - 243_rocky_9 or 6.2.  So I don't make a pull request for the wrong branch.</p>",
        "id": 451861668,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721163435
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> I could attempt to merge the 6.2 branch with Rocky9, if you like? I'm happy to schedule a meeting. The httpd portion of Dataverse-Ansible is entirely untested. LetsEncrypt refuses to issue certs for addresses ending in <a href=\"http://amazon.com\">amazon.com</a>, so that code is theoretical.</p>",
        "id": 452059540,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1721220101
    },
    {
        "content": "<p>I'm going to wait for Tim and Kristian but wondering if I should just do the fresh install with 6.0 or 6.1 and then do conventional updates?  </p>\n<div class=\"codehilite\"><pre><span></span><code>\n</code></pre></div>",
        "id": 452115285,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721231768
    },
    {
        "content": "<p>How are most people doing a fresh install?</p>",
        "id": 452124758,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721233789
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"598186\">Don Sizemore</span> do you think it might help <span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> and <span class=\"user-mention\" data-user-id=\"736518\">@Kristian Allen - UCLA</span> using the way I'm upgrading with migrations and all?</p>",
        "id": 452125519,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1721233927
    },
    {
        "content": "<p>Since the ansible script for 6.2 doesn't seem to be working I'm happy to hear suggestions</p>",
        "id": 452126677,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721234147
    },
    {
        "content": "<p>I can't upgrade from 5.14 because RHEL7 hit endoflife.  Have to do a fresh install (on rocky9)</p>",
        "id": 452126921,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721234196
    },
    {
        "content": "<p>It's the letsencrypt part that fails.   We're going to try yet again and install lets encrypt after the fact. But I'd still like to know how other people are doing fresh installs.  <br>\nSuccessfully, that is.</p>",
        "id": 452128680,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721234645
    },
    {
        "content": "<p>Have you tried disabling the Let's Encrypt part from the DV Ansible? And then using another role that has been tested working on RHEL 9 or doing it manually?</p>",
        "id": 452136780,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1721236544
    },
    {
        "content": "<p>Just to get stuff going...</p>",
        "id": 452136830,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1721236554
    },
    {
        "content": "<p>In the 6.2 ansible script, letsencrypt out-of-the-box is disabled.  We're going to test again on a fresh Rocky 9 and see how that goes.</p>",
        "id": 452139339,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721237016
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"626369\">@Don Sizemore</span> Would you have any time to meet on a friday?</p>",
        "id": 452172169,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721245337
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"598183\">@Oliver Bertuch</span> Dataverse-Ansible works with RHEL9, but IIRC that (finally) got merged after the 6.2 branch</p>",
        "id": 452179886,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1721247547
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> I think I should be able to meet late Friday morning or in the afternoon? You'll appreciate that a test server here started inexplicably receiving 403 Forbiddens from AWS S3. No config changes.</p>",
        "id": 452179988,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1721247585
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> on your 403 Forbiddens: did you update your CORS rules per the CORS section of <a href=\"https://github.com/IQSS/dataverse/releases/v5.12\">https://github.com/IQSS/dataverse/releases/v5.12</a> ?</p>",
        "id": 452182509,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1721248326
    },
    {
        "content": "<p>We're still back at getting letsencrypt working but I believe I did since we were at 5.14</p>",
        "id": 452189994,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721249917
    },
    {
        "content": "<p>We're in a different time zone but morning or afternoon is fine.  Are you on EST?</p>",
        "id": 452190083,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721249946
    },
    {
        "content": "<p>12:30 or 1pm our time? I'll figure out pst to your time</p>",
        "id": 452190972,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721250188
    },
    {
        "content": "<p>we're EDT time but I'm getting 403 Forbiddens on a test server, so I'm interesting in comparing notes there.</p>",
        "id": 452352324,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1721311244
    },
    {
        "content": "<p>What's a good time for you?</p>",
        "id": 452371249,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721315630
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> I have a 9:45 EDT with Sonia, but other than that I'm free. On the 403 forbiddens: how are you defining your S3 credentials?</p>",
        "id": 452394671,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1721322359
    },
    {
        "content": "<p>Dealing with the letsencrypt and certbot somewhat distracted me from the s3 buckets.  I'm getting back to that today</p>",
        "id": 452396498,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721322907
    },
    {
        "content": "<p>I should add that I need a working system to deal with the s3 buckets and at this time I don't have that.  I'm wondering how other people do their installations or migration installations.  Ansible script or the manual installl.</p>",
        "id": 452417213,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721328465
    },
    {
        "content": "<p>I have a working test dataverse and some worI hking s3 buckets.  I'm using Oliver Oliver Bertuch's example:<br>\ndataverse.files.bucket1.storage-driver-id=s3<br>\n<a href=\"http://dataverse.files.bucket1.s3.xxx\">dataverse.files.bucket1.s3.xxx</a><br>\n...<br>\ndataverse.files.bucket2.storage-driver-id=s3<br>\n<a href=\"http://dataverse.files.bucket2.s3.xxx\">dataverse.files.bucket2.s3.xxx</a><br>\n...<br>\ndataverse.files.bucket3.storage-driver-id=s3<br>\n<a href=\"http://dataverse.files.bucket3.s3.xxx\">dataverse.files.bucket3.s3.xxx</a><br>\n...<br>\ndataverse.files.bucket4.storage-driver-id=s3<br>\n<a href=\"http://dataverse.files.bucket4.s3.xxx\">dataverse.files.bucket4.s3.xxx</a></p>\n<p>That each bucket needs to have it's own storage-id</p>",
        "id": 453553077,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721778665
    },
    {
        "content": "<p>It still looks a little off to me but if it's working, great!</p>",
        "id": 453696664,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1721827857
    },
    {
        "content": "<p>The above is example is from <span class=\"user-mention\" data-user-id=\"598183\">@Oliver Bertuch</span> .  I guess what I had been trying to verify is if every bucket needs it's own storage-driver  - it they are all the same storage type.</p>",
        "id": 453732783,
        "sender_full_name": "jamie jamison",
        "timestamp": 1721836353
    },
    {
        "content": "<p>Our current theory is to do a fresh install of 6.3 via Ansible (this is working), then migrate the database from 5.14 to 6.3 via Flyway. Does this make sense or does anyone see any areas to be aware of? <br>\nThe thinking was <a href=\"https://github.com/IQSS/dataverse/blob/0d279573bb8d7c96d7a4a1dc4b66b2258059dfba/src/main/java/edu/harvard/iq/dataverse/flyway/StartupFlywayMigrator.java#L16\">https://github.com/IQSS/dataverse/blob/0d279573bb8d7c96d7a4a1dc4b66b2258059dfba/src/main/java/edu/harvard/iq/dataverse/flyway/StartupFlywayMigrator.java#L16</a> can be run on own? <br>\nOr is there a cleaner way to do this via pulling objects out and putting back in via DVN API?</p>",
        "id": 455480394,
        "sender_full_name": "Kristian Allen - UCLA",
        "timestamp": 1722458610
    },
    {
        "content": "<p>I mean, people have pulled off similar feats but officially we ask that you step through each upgrade. (We know this is painful.)</p>",
        "id": 455483654,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1722459637
    },
    {
        "content": "<p>I don't think the step through upgrade path would work in our case as our 5.14 instance is on older version of RHEL and we have to move to a new OS (Rocky), so we were trying to determine a path forward</p>",
        "id": 455494353,
        "sender_full_name": "Kristian Allen - UCLA",
        "timestamp": 1722463872
    },
    {
        "content": "<p>I think we'll power forward with the manual migration but keep meticulous notes and then we'll make sure to write up for the community</p>",
        "id": 455514696,
        "sender_full_name": "Kristian Allen - UCLA",
        "timestamp": 1722473287
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"736518\">@Kristian Allen - UCLA</span> I personally think that your new server is a great spot to migrate/upgrade from 5.14 to 6.0, then carry on to 6.3.</p>",
        "id": 455626846,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1722513229
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"736518\">@Kristian Allen - UCLA</span> you might be interested in this \"Our experience on upgrading dataverse from 4.2.2 to 6.1 in a non-standard way\" thread: <a href=\"https://groups.google.com/g/dataverse-community/c/BUO37-reWIs/m/18SK0DZlAQAJ\">https://groups.google.com/g/dataverse-community/c/BUO37-reWIs/m/18SK0DZlAQAJ</a></p>",
        "id": 455655521,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1722520413
    },
    {
        "content": "<p>I have been doing experiments on a similar migration from 4.20 to 6.3 using Flyway only as well.</p>",
        "id": 456289293,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1722761425
    },
    {
        "content": "<p>You can find the necessary extra migrations you will need when using Flyway only here: <a href=\"https://jugit.fz-juelich.de/fdm/dev/dataverse/-/tree/juelich-data-upgrade/src/main/resources/db/extra?ref_type=heads\">https://jugit.fz-juelich.de/fdm/dev/dataverse/-/tree/juelich-data-upgrade/src/main/resources/db/extra?ref_type=heads</a></p>\n<p>Obviously, you'll only need the 5.14+ migrations, not the others.</p>",
        "id": 456289375,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1722761488
    },
    {
        "content": "<p>I've also added the Flyway Maven Plugin in this branch to the DV app POM. <a href=\"https://jugit.fz-juelich.de/fdm/dev/dataverse/-/blob/juelich-data-upgrade/pom.xml?ref_type=heads#L755\">https://jugit.fz-juelich.de/fdm/dev/dataverse/-/blob/juelich-data-upgrade/pom.xml?ref_type=heads#L755</a></p>",
        "id": 456289453,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1722761543
    },
    {
        "content": "<p>I can share more details about how I used a few local containers to get the job done if that helps.</p>",
        "id": 456289478,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1722761568
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"626369\">Don Sizemore</span> <a href=\"#narrow/stream/378866-troubleshooting/topic/Upgrading.205.2E14.20to.206.2E2/near/455626846\">said</a>:</p>\n<blockquote>\n<p><span class=\"user-mention silent\" data-user-id=\"736518\">Kristian Allen - UCLA</span> I personally think that your new server is a great spot to migrate/upgrade from 5.14 to 6.0, then carry on to 6.3.</p>\n</blockquote>\n<p><span class=\"user-mention\" data-user-id=\"626369\">@Don Sizemore</span>   I'm trying to install a fresh test 5.14    Directions say \"may be installed using branches tagged with that version\".  What is the correct syntax to tag the version?</p>\n<p>Would this look like:   **</p>\n<p>git clone <a href=\"https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible.git\">https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible.git</a> dataverse-5.14<br>\n**</p>",
        "id": 456706212,
        "sender_full_name": "jamie jamison",
        "timestamp": 1722891486
    },
    {
        "content": "<p>I might get this wrong, but I believe it refers to the tagging on the Dataverse side.</p>\n<p>I think you'd change this from \"version:6.3\" to whatever version you want but I'm not sure if it \"just works\": <a href=\"https://github.com/gdcc/dataverse-ansible/blob/c1e21f255dd00bf5d95c2a6a807ae7579974361b/defaults/main.yml#L264\">https://github.com/gdcc/dataverse-ansible/blob/c1e21f255dd00bf5d95c2a6a807ae7579974361b/defaults/main.yml#L264</a></p>",
        "id": 456707460,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1722891998
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"598183\">Oliver Bertuch</span> <a href=\"#narrow/stream/378866-troubleshooting/topic/Upgrading.205.2E14.20to.206.2E2/near/456289478\">said</a>:</p>\n<blockquote>\n<p>I can share more details about how I used a few local containers to get the job done if that helps.</p>\n</blockquote>\n<p><span class=\"user-mention\" data-user-id=\"598183\">@Oliver Bertuch</span>      Yes, some details on how this is used would help.</p>",
        "id": 456713603,
        "sender_full_name": "jamie jamison",
        "timestamp": 1722894419
    },
    {
        "content": "<p>Ok so here's a quick list of tasks:</p>\n<ol>\n<li>Make a <code>pg_dump</code> of your current database into a file <code>dump.sql</code></li>\n<li>Copy that file to your dev machine (or wherever you have Maven and Java SDK around)</li>\n<li>Make sure you have installed Docker on that machine as well (you could also use some arbitrary Linux cloud host if that's easier to get Docker up and running)</li>\n<li>Download this <a href=\"/user_uploads/53090/nUhAgnhM1L4j0k_7OiwsbNtx/compose.yaml\">compose.yaml</a> and put it next to your <code>dump.sql</code> file.</li>\n<li>Run <code>docker compose up</code> to start a PG container exposed on port 54321</li>\n<li>Apply my <a href=\"https://jugit.fz-juelich.de/fdm/dev/dataverse/-/commit/329ac9f81cae8c727b21effc5f41ed1b7e16f4d3#442292b8a7efeabbe4cc176709b833b1792140ec\">POM patch</a> to enable using the Flyway migrations locally</li>\n<li>Get all the extra migrations you need that have a version number larger than your current Dataverse version (that'll be <a href=\"https://jugit.fz-juelich.de/fdm/dev/dataverse/-/commit/329ac9f81cae8c727b21effc5f41ed1b7e16f4d3#4f39728b19a576cb30c5acee5fa1d3495b3e5db4\">this one</a> and <a href=\"https://jugit.fz-juelich.de/fdm/dev/dataverse/-/commit/329ac9f81cae8c727b21effc5f41ed1b7e16f4d3#a2ba977edd2c98f6f426ad7519b2693e283f6dd1\">this one</a> and put them under <code>src/main/resources/db/extra</code></li>\n<li>Now checkout the Flyway migrations missing from the containerized DB: <code>mvn flyway:info</code>. You should see that some migrations are missing.</li>\n<li>Now apply the migrations: <code>mvn flyway:migrate -Dflyway.outOfOrder</code></li>\n<li>Check migrations again, should be all applied now: <code>mvn flyway:info</code></li>\n<li>Now move the migrations from the <code>extra</code> folder or comment out that location in the POM - the idea is to make them unavailable again, as we don't want them around for all eternity or during the next upgrade.</li>\n<li>Now let's remove these migrations to be 100% upstream compatible again: <code>mvn flyway:repair</code></li>\n<li>Running <code>mvn flyway:info</code> again should no longer list our two extra migrations!</li>\n<li>Now make another dump of the migrated database: <code>docker exec -it data-next-postgres pg_dump -U dataverse &gt; dump-v6.3.sql</code></li>\n<li>You can load this database into some other Postgres database now and deploy Dataverse 6.3, configuring DV to use this DB.</li>\n<li>Cleanup by running <code>docker compose down</code></li>\n</ol>",
        "id": 456783800,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1722928108
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> you want to clone the 5.14 branch: <code>$ git clone -b 5.14 https://github.com/gdcc/dataverse-ansible.git 5.14</code></p>",
        "id": 456845402,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1722947665
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"626369\">Don Sizemore</span> <a href=\"#narrow/stream/378866-troubleshooting/topic/Upgrading.205.2E14.20to.206.2E2/near/456845402\">said</a>:</p>\n<blockquote>\n<p><span class=\"user-mention silent\" data-user-id=\"653479\">jamie jamison</span> you want to clone the 5.14 branch: <code>$ git clone -b 5.14 https://github.com/gdcc/dataverse-ansible.git 5.14</code></p>\n</blockquote>\n<p>Tried that and ran ansible:  **</p>\n<p>ansible-playbook --connection=local -vvv -i 5.14/inventory 5.14/dataverse.pb -e \"@5.14/defaults/main.yml\"<br>\n**<br>\nUnfortunately failed at  step: [dataverse : install java-nnn-openjdk and other packages for RedHat/Rocky] <strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong><strong>*</strong>task path: /home/rocky/dataverse/tasks/dataverse-prereqs.yml:63</p>\n<p>Huge, long error message.  Don't know if you want to see that.</p>",
        "id": 456955471,
        "sender_full_name": "jamie jamison",
        "timestamp": 1722978408
    },
    {
        "content": "<p>Possible java verson error:    **</p>\n<p>fatal: [localhost]: FAILED! =&gt; {</p>\n<p>\"msg\": \"An unhandled exception occurred while templating '{'version': 11, 'home': '/usr/lib/jvm/java-{{ java.version}}'}'. Error was a &lt;class 'ansible.errors.AnsibleError'&gt;, original<br>\n**</p>",
        "id": 456955715,
        "sender_full_name": "jamie jamison",
        "timestamp": 1722978524
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"653479\">@jamie jamison</span> sigh. that again. someone else introduced a reflexive group_var without testing the role. two quick fixes could be to either edit tasks/dataverse-prereqs.yml and hard-code <code>11</code> or better yet in group_vars for the <code>java.home</code> variable - either should get you going. Solr mirrors tend to remove old versions, so if it dies downloading Solr, you can give it a custom Solr download url in group_vars pointing to <a href=\"http://archive.apache.org\">archive.apache.org</a>.</p>",
        "id": 456980437,
        "sender_full_name": "Don Sizemore",
        "timestamp": 1722990420
    },
    {
        "content": "<p>I finally was able to restore the test.dataverse 5.14 from an aws snapshot.   I'm going to keep the notes on restring earlier versions.  Might be helpful for other projects.</p>",
        "id": 459302996,
        "sender_full_name": "jamie jamison",
        "timestamp": 1723155445
    }
]