[
    {
        "content": "<p>Posted on: <a href=\"https://github.com/IQSS/dataverse/issues/9949\">#9949</a> </p>\n<p>One thing to notice at least on the windows side (probably a separate issue), and I am not sure this happens across all the platforms but the first time the containers start,  configbaker will not be able to connect to [http://dataverse:8080/api/info/version] </p>\n<p><a href=\"/user_uploads/53090/LChhGz_2riqUtT07-bYI-PW7/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/LChhGz_2riqUtT07-bYI-PW7/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/LChhGz_2riqUtT07-bYI-PW7/image.png\"></a></div><p>After login to the payara server at localhost:4848 and checking the applications deployed, nothing shows up. </p>\n<p><a href=\"/user_uploads/53090/goTy4kCkQcnWsiRqgtEnzNj_/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/goTy4kCkQcnWsiRqgtEnzNj_/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/goTy4kCkQcnWsiRqgtEnzNj_/image.png\"></a></div><p>To get around this for me was necessary to restart all the containers with mvn -Pct docker:run or it also works if I individually restart the dataverse-1 container with docker desktop.</p>\n<p><a href=\"/user_uploads/53090/_B31ixs0AwZff1acZqU1ltZU/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/_B31ixs0AwZff1acZqU1ltZU/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/_B31ixs0AwZff1acZqU1ltZU/image.png\"></a></div>",
        "id": 392581966,
        "sender_full_name": "Juan Pablo Tosca Villanueva",
        "timestamp": 1695408494
    },
    {
        "content": "<p>Thanks, so the \"run\" command doesn't \"just work\" for you. You have to restart the dataverse container. Very strange.</p>",
        "id": 392582122,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1695408575
    },
    {
        "content": "<p>The server is running but the application is not deployed.</p>",
        "id": 392582429,
        "sender_full_name": "Juan Pablo Tosca Villanueva",
        "timestamp": 1695408721
    },
    {
        "content": "<p>Sure. Payara is running. So strange.</p>",
        "id": 392582782,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1695408855
    },
    {
        "content": "<p>Well, if you're having this problem, probably others are too, so I appreciate the bug report.</p>",
        "id": 392582848,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1695408885
    }
]